### ISSUE TITLE
Sonos S1 und S2 Systeme im Iobroker 

### ISSUE THREAD

**Issue by holler22** [ioBroker/ioBroker.sonos#119]
**Describe the bug**  

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**  

Ist es möglich 2 Systeme über den Iobroker zu steuern. 
Die Geräte im S2 App werden erkannt.
Die Play 5 1 Gen nicht

**Comment by MMeinhardt1** [comment]
Bei mir funktionieren die Play 5 1. Generation ohne Probleme.
