### ISSUE TITLE
Keine Steuerung möglich, obwohl Web-Frontend funktioniert

### ISSUE THREAD

**Issue by simon-iobroker** [ioBroker/ioBroker.sonos#12]
Mein iobroker läuft auf meinem Synology-Server und ist mit Amazon Alexa per iobroker cloud verbunden. Ich habe Sonos als Smart Gerät eingebunden und steuere es so per Sprache an.
Die Sonos-Steuerung per Adapter-Webseite funktioniert einwandfrei, alle Sonos-Geräte werden erkannt.
Leider funktioniert aber die Sprachsteuerung nicht, der Sonos-Adapter tut trotz ansteuerung (im Log sichtbar) nichts. Auch die Ausgabe der Bestätigung per sayit kommt nicht an.
Hier das Log:
`
sayit.0	2017-02-17 23:44:00.255	info	sayit.0 Copied file "/opt/iobroker/node_modules/iobroker.sayit/say.mp3" to "/opt/iobroker/cache/f3879be4ea7d254b3a90e80f147c78a5.mp3"
sayit.0	2017-02-17 23:44:00.254	info	sayit.0 Send to sonos 70;http://192.168.0.122:8082/state/sayit.0.tts.mp3
DiskStation	2017-02-17 23:44:00.144	info	host.DiskStation Restart adapter system.adapter.sonos.0 because enabled
DiskStation	2017-02-17 23:44:00.143	error	host.DiskStation instance system.adapter.sonos.0 terminated with code 0 (OK)
sonos.0	2017-02-17 23:44:00.103	info	sonos.0 terminating
sonos.0	2017-02-17 23:44:00.103	error	sonos.0 TypeError: fileName.indexOf is not a function at text2speech (/opt/iobroker/node_modules/iobroker.sonos/sonos.js:576:24) at Adapter. (/opt/iobroker/node_modules/iobroker.son
sonos.0	2017-02-17 23:44:00.103	error	sonos.0 uncaught exception: fileName.indexOf is not a function
sonos.0	2017-02-17 23:44:00.103	info	sonos.0 try to control id sonos.0.root.192_168_0_227.tts with {"val":false,"ack":false,"ts":1487371440087,"q":0,"from":"system.adapter.cloud.0","lc":1487371440087}
sayit.0	2017-02-17 23:44:00.080	info	sayit.0 saying: Sonos Wohnzimmer ist ausgeschaltet!
sonos.0	2017-02-17 23:39:53.908	info	sonos.0 http sonos server listening on port 8080
sonos.0	2017-02-17 23:39:53.905	info	sonos.0 starting. Version 1.4.2 in /opt/iobroker/node_modules/iobroker.sonos, node: v4.4.2
DiskStation	2017-02-17 23:39:52.040	info	host.DiskStation instance system.adapter.sonos.0 started with pid 20004
sayit.0	2017-02-17 23:39:22.150	info	sayit.0 Copied file "/opt/iobroker/node_modules/iobroker.sayit/say.mp3" to "/opt/iobroker/cache/8df2f0414f57e3e1780155b37813da40.mp3"
sayit.0	2017-02-17 23:39:22.145	info	sayit.0 Send to sonos 70;http://192.168.0.122:8082/state/sayit.0.tts.mp3
DiskStation	2017-02-17 23:39:22.028	info	host.DiskStation Restart adapter system.adapter.sonos.0 because enabled
DiskStation	2017-02-17 23:39:22.028	error	host.DiskStation instance system.adapter.sonos.0 terminated with code 0 (OK)
sonos.0	2017-02-17 23:39:21.995	info	sonos.0 terminating
sonos.0	2017-02-17 23:39:21.995	error	sonos.0 TypeError: fileName.indexOf is not a function at text2speech (/opt/iobroker/node_modules/iobroker.sonos/sonos.js:576:24) at Adapter. (/opt/iobroker/node_modules/iobroker.son
sonos.0	2017-02-17 23:39:21.995	error	sonos.0 uncaught exception: fileName.indexOf is not a function
sonos.0	2017-02-17 23:39:21.994	info	sonos.0 try to control id sonos.0.root.192_168_0_227.tts with {"val":true,"ack":false,"ts":1487371161977,"q":0,"from":"system.adapter.cloud.0","lc":1487371109860}
sayit.0	2017-02-17 23:39:21.977	info	sayit.0 saying: Sonos Wohnzimmer ist eingeschaltet!
sonos.0	2017-02-17 23:38:32.750	info	sonos.0 http sonos server listening on port 8080
sonos.0	2017-02-17 23:38:32.746	info	sonos.0 starting. Version 1.4.2 in /opt/iobroker/node_modules/iobroker.sonos, node: v4.4.2
DiskStation	2017-02-17 23:38:30.906	info	host.DiskStation instance system.adapter.sonos.0 started with pid 19706
sayit.0	2017-02-17 23:38:30.038	info	sayit.0 Copied file "/opt/iobroker/node_modules/iobroker.sayit/say.mp3" to "/opt/iobroker/cache/8df2f0414f57e3e1780155b37813da40.mp3"
sayit.0	2017-02-17 23:38:30.031	info	sayit.0 Send to sonos 70;http://192.168.0.122:8082/state/sayit.0.tts.mp3
sayit.0	2017-02-17 23:38:29.870	info	sayit.0 saying: Sonos Wohnzimmer ist eingeschaltet!
sayit.0	2017-02-17 23:38:01.144	info	Copied file "/opt/iobroker/node_modules/iobroker.sayit/say.mp3" to "/opt/iobroker/cache/f3879be4ea7d254b3a90e80f147c78a5.mp3"
sayit.0	2017-02-17 23:38:01.128	info	Send to sonos 70;http://192.168.0.122:8082/state/sayit.0.tts.mp3
host.DiskStation	2017-02-17 23:38:00.889	info	Restart adapter system.adapter.sonos.0 because enabled
host.DiskStation	2017-02-17 23:38:00.888	error	instance system.adapter.sonos.0 terminated with code 0 (OK)
sonos.0	2017-02-17 23:38:00.852	info	terminating
sonos.0	2017-02-17 23:38:00.851	error	at Timer.listOnTimeout (timers.js:92:15)
sonos.0	2017-02-17 23:38:00.851	error	at null._onTimeout (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:2870:38)
sonos.0	2017-02-17 23:38:00.851	error	at Adapter.emit (events.js:172:7)
sonos.0	2017-02-17 23:38:00.851	error	at emitTwo (events.js:87:13)
sonos.0	2017-02-17 23:38:00.851	error	at Adapter. (/opt/iobroker/node_modules/iobroker.sonos/sonos.js:146:17)
sonos.0	2017-02-17 23:38:00.851	error	at text2speech (/opt/iobroker/node_modules/iobroker.sonos/sonos.js:576:24)
sonos.0	2017-02-17 23:38:00.851	error	TypeError: fileName.indexOf is not a function
sonos.0	2017-02-17 23:38:00.844	error	uncaught exception: fileName.indexOf is not a function
`

**Comment by GermanBluefox** [comment]
Warum steuerst du sonos.0.root.192_168_0_227.tts ?

Das ist Endpunkt um Text vor zu lesen.  Du brauchst sonos.0.root.192_168_0_227.state_simple

**Comment by simon-iobroker** [comment]
Manchmal sind die Fehler so klein und man merkt es doch nicht! Vielen Dank - jetzt klappts, ich hatte wohl daneben geklickt.
