### ISSUE TITLE
wrongly allocated devices across multiple instances

### ISSUE THREAD

**Issue by steffensammet** [ioBroker/ioBroker.sonos#148]
Hi there,

I am currently running 3 Sonos AMPs and one Sonos Play:1. As I am powering down the AMPs every night, I typically recieved an error message saying the instance have been terminated. To workaround this, I splitted my Sonos devices across 2 instances; and immediatly before powering down the AMPs, I close the instance where they are located.

Now strangly, the second instance with only the Play:1 shows me error message about the AMPs on the first instance.

![image](https://user-images.githubusercontent.com/38013126/158887068-6e17c039-f1c1-4476-8c9a-530f96fe4c17.png)

There is no 192.168.178.86 / 87 / 88 existing

![image](https://user-images.githubusercontent.com/38013126/158887300-8a88861b-7117-4d17-b1ac-9f6f6044108d.png)

Now I can only guess; do the 2 instances share one configuration ?

Thanks,
Steffen

**Versions:**  
 - Adapter version: 2.1.7
 - JS-Controller version: 4.0.21
 - Node version: 14.19.0
 - Operating system: Rasbian Buster

**Comment by Apollon77** [comment]
The "members" log is fixed on GitHub already ... is it this what you talk here? If not please be more exact

**Comment by steffensammet** [comment]
Hi Apollon,

lets change to German :-)

Ich nutze die 2.1.7; die aus Github ist ja die gleiche wie im offiziellen Repositry.
Im Grund habe ich das gleiche Problem wie hier: [](https://github.com/ioBroker/ioBroker.sonos/issues/150). Mein Workaround war eben die Geräte in verschiedene Instanzen zu untergliedern.

Die Instanz "0" enthält 3 AMPs, die Instanz "1" enthält einen Play:1. Warum auch immer, denkt der Adapter dass es in die Instanz "1" ebenfalls die AMPs gibt (ein Phantom ?? wahrscheinlich gibt es auch ein Phantom des Play:1 in der Instanz "0")

**Comment by Apollon77** [comment]
> die aus Github ist ja die gleiche wie im offiziellen Repositry.

Von der Nummer her ja,. vom Code her nicht. Daher bitte probieren

**Comment by steffensammet** [comment]
> > die aus Github ist ja die gleiche wie im offiziellen Repositry.
> 
> Von der Nummer her ja,. vom Code her nicht. Daher bitte probieren

Hat geklappt. Danke! :-)
