### ISSUE TITLE
Sonos Instanz stürzt ständig ab - Restart loop detected

### ISSUE THREAD

**Issue by mdaudi1982** [ioBroker/ioBroker.sonos#155]
Hallo,

Ich habe seit ein paar Wochen das Problem, dass mein Sonos Adapter ständig abstürzt.
![Probleme beim häufigen abstürzenden Adapterinstanzen - Sonos](https://user-images.githubusercontent.com/82971021/170785680-88c0b8dc-a42f-4e7d-9aad-189dfd2966b0.jpg)

Ich habe jedoch keine Restart Zeiten angegeben.
Ich kann einfach nicht herausfinden, woran das liegt. Habe auch im Log nichts gefunden. 
Hat jemand eine Idee, woran das liegen könnte?

Gruß,
Micha

**Comment by Apollon77** [comment]
Also wenn Sie abstürzt dann mal zum genannten Zeitpunkt im Log schauen. Da muss was zu sehen sein

**Comment by mdaudi1982** [comment]
Also ich habe eben mal reingesehen. Der Adapter ist zwar heute noch nicht abgestürzt, hat aber einige Fehlermeldungen und Warnungen protokolliert. 

![Protokolle](https://user-images.githubusercontent.com/82971021/170819660-a76a1202-a0c4-4bfa-9065-43a830fcbaf7.jpg)

**Comment by mczeus** [comment]
habe was ähnliches!
`<html><body>


host.iobroker | 2022-06-03 07:38:04.022 | error | instance system.adapter.sonos.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
sonos.0 | 2022-06-03 07:38:03.401 | error | Cannot read property 'members' of undefined
sonos.0 | 2022-06-03 07:38:03.401 | error | TypeError:  Cannot read property 'members' of undefined    at Player.setGroupVolume   (/opt/iobroker/node_modules/sonos-discovery/lib/prototypes/Player/setGroupVolume.js:17:25)     at Adapter.<anonymous>  (/opt/iobroker/node_modules/iobroker.sonos/main.js:203:38)    at  Adapter.emit (events.js:400:28)    at Immediate.<anonymous>  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5379:53)     at processImmediate (internal/timers.js:464:21)
sonos.0 | 2022-06-03 07:38:03.400 | error | uncaught exception: Cannot read property 'members' of undefined


</body>
</html>

bin der Meinung das kommt erst seit ich den NPM von 12 auf Node.js v14.19.3`hochgezogen habe
der Zigbee adapter macht auch mucken und startet öfter neu.

**Comment by mdaudi1982** [comment]
Da Gefühl mit dem Update von Node.js habe ich auch, kann es aber nicht sicher sagen. Anfangs (vor ca. einem Jahr) funktionierte es ganz gut. Seit ein paar Wochen hängt er sich ständig auf. Gibt es Lösungsmöglichkeiten?

**Comment by mdaudi1982** [comment]
Any solutions on this?

**Comment by Apollon77** [comment]
The " Cannot read property 'members' of undefined" is fixed on GitHub.

In #150 we test something for the EHOSTUNREACH and ECONNRESET cases ... but wild try

**Comment by mczeus** [comment]
vielen Dank, bis jetzt keine Meldungen mehr!
