### ISSUE TITLE
Naming missmatch 'group-volume'

### ISSUE THREAD

**Issue by gaga191281** [ioBroker/ioBroker.sonos#163]
Laut Log wird ein Datenpunkt mit dem Namen `group-volume` erwartet. In den angelegten Datenpunkten heißt dieser jedoch `group_volume`. 
Auswirkung: Setzen des Datenpunktwertes funktioniert. Wird die Gruppenlautstärke jedoch von außerhalb geändert wird der Datenpunkt nicht aktualisiert.

LOG:
<html>
<body>

sonos.0 | Zeit | debug | Nachricht
-- | -- | -- | --
sonos.0 | 2022-06-15 10:50:15.386 | warn | State "sonos.0.root.192_168_188_77.group-volume" has no existing object, this might lead to an error in future versions
sonos.0 | 2022-06-15 10:50:15.362 | warn | State "sonos.0.root.192_168_188_89.group-volume" has no existing object, this might lead to an error in future versions
sonos.0 | 2022-06-15 10:50:15.360 | warn | State "sonos.0.root.192_168_188_48.group-volume" has no existing object, this might lead to an error in future versions
sonos.0 | 2022-06-15 10:50:15.358 | warn | State "sonos.0.root.192_168_188_57.group-volume" has no existing object, this might lead to an error in future versions
sonos.0 | 2022-06-15 10:50:15.355 | warn | State "sonos.0.root.192_168_188_73.group-volume" has no existing object, this might lead to an error in future versions
sonos.0 | 2022-06-15 10:50:15.354 | warn | State "sonos.0.root.192_168_188_47.group-volume" has no existing object, this might lead to an error in future versions
sonos.0 | 2022-06-15 10:50:15.352 | warn | State "sonos.0.root.192_168_188_40.group-volume" has no existing object, this might lead to an error in future versions
sonos.0 | 2022-06-15 10:50:15.325 | warn | State "sonos.0.root.192_168_188_39.group-volume" has no existing object, this might lead to an error in future versions

</body>
</html>

**Comment by Apollon77** [comment]
Please install latest version 2.2.2
