### ISSUE TITLE
Set play queue with Playlist or Album from music library

### ISSUE THREAD

**Issue by HJS72** [ioBroker/ioBroker.sonos#165]
Is it possible to set the current queue with a playlist name or an album name from the music library?
The number of favorites is limited in the system so favorites_set is not the solution.

**Comment by udondan** [comment]
Supporting Sonos **playlists** for me is an essential feature. Favorites are just very badly impemented on Sonos side. Favorites with many items are extreeeeeeemly slow. For instance, favorites with 1000 items take ~15 seconds to load before they start playing. A native Sonos playlist with the same items immediately starts. It also seems like items sometimes are not loading at all on large favorite lists, playing is stopped and there is a delay between tracks of ~2 seconds.

You may think, why would I have a playlist with 1000 items? Well, that's actually very common in children audio plays. All episodes of Spongebob have 1001 items, All episodes of PAW Patrol currently have 2590 items and still growing.

---

Support for playing **albums**... not sure how this should work. Sonos itself has no albums. Those are elements of a streaming service. Then album titles are not unique. Same titles exist from multiple artist. For directly selecting an album you would need to _set_ the streaming service and artist name together with the album.
