### ISSUE TITLE
Adding control for new parameter - track number - only working partly

### ISSUE THREAD

**Issue by Rello** [ioBroker/ioBroker.sonos#166]
Hello,

I want to add the control for the track number. working on a pull, but not working yet.
I need some help - I thought I understood the coding, but no...

---
**Implementation**

I add a new channel state for `track_number`
https://github.com/Rello/ioBroker.sonos/blob/patch-1/main.js#L419-L427
```
       'track_number': {
            def:    '',
            type:   'string',
            read:  true,
            write: true,
            role:  'media.trackNo',
            desc:  'Track Number',
            name:   'Track Number'
   	},
```

I add a new action when the value is changed from IO
https://github.com/Rello/ioBroker.sonos/blob/patch-1/main.js#L77-L78
```
if (id.state === 'track_number') {
    promise = player.trackSeek(state.val);
} 
```

This action uses the existing `player.trackSeek(state.val);` from the sonos-discovery
https://github.com/jishi/node-sonos-discovery/blob/de6771b0ec8713ea8028560456cda593c8283372/lib/models/Player.js#L551

I add the adapter update when the update from Sonos is received
`adapter.setState({device: 'root', channel: ip, state: 'track_number'},   {val: sonosState.trackNo, ack: true});`
https://github.com/Rello/ioBroker.sonos/blob/patch-1/main.js#L1351

---
**Testing**

The value in the Object list is updated - so this way works.
When I try to change the trackNo, I get an error.
Log:
`try to control id sonos.0.root.192_168_0_27.track_number with {"val":1,"ack":false,"ts":1656748575050,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1656748575050}`

`RequestFailedError: Got status 500 when invoking /MediaRenderer/AVTransport/Control`
---
any idea what I am missing?

**Comment by Apollon77** [comment]
No idea because the error 500 comes from the sonos device ... Do you call the player.trackSeek() method with the right parameters?

**Comment by Rello** [comment]
Hi,
according to some commented code in main.js, its just the track number
https://github.com/ioBroker/ioBroker.sonos/blob/master/main.js#L1518

according to the Sonos API description, its just the number as string
https://svrooij.io/sonos-api-docs/services/av-transport.html#seek

not much difference to the player.timeSeek

but something small seems to be missing...

**Comment by Rello** [comment]
It is working now!
Will do some cleanup & testing and submit a push then
thank yo9u

**Comment by Rello** [comment]
https://github.com/ioBroker/ioBroker.sonos/pull/167
