### ISSUE TITLE
Fehlermeldung "... no existing object, this might ..."

### ISSUE THREAD

**Issue by MMeinhardt1** [ioBroker/ioBroker.sonos#168]
Hi,

ich bekomme immer wieder folgende Fehlermeldung,

sonos.0 | 2022-07-09 16:04:25.406 | warn | State "sonos.0.root.XXX_XXX_XXX_XXX.current_track_number" has no existing object, this might lead to an error in future versions
-- | -- | -- | --

Vielen Dank

**Comment by justr1** [comment]
Habe bei mir den kompletten sonos.0-Objektbaum gelöscht. Dieser wird beim Start der Sonos-Instanz neu angelegt und da war dann auch das neue Objekt "current_track_number" dabei.

HTH und viele Grüße
