### ISSUE TITLE
Scan nach Sonos ohne Funktion

### ISSUE THREAD

**Issue by funk01** [ioBroker/ioBroker.sonos#17]
Hi,
Installation lief ohne Fehler im Log unter Docker / Synology DS 916+. 
Config-Menü öffnet und zeigt alle Optionen. Ein Klick auf "Scan" bleibt ohne Werte. Auch "Räume" bleibt leer. 
Trägt man die IP der Sonos per Hand ein, so findet er auch keine Sonos. Die Webansicht öffnet, aber alle Felder sind leer. Es gibt nur ein Subnetz; Sonos und ioBroker arbeiten in gleicher IP-Umgebung mit 192.168.178.45 + .46 für Sonos und x.x.x.1 an Fritzbox. Any Idea?

**Comment by matthiasgasser** [comment]
Hi,

ein bisschen spät vielleicht aber...

wenn der Docker nicht in der Bridge läuft funktioniert die Sonos Suche und Steuerung gut.

**Comment by GermanBluefox** [comment]
Ich mache Issue zu. Ich denke, dass da Multicasts extra eingeschaltet werden müssen.
