### ISSUE TITLE
Datenpunkt Favorites set ohne Funktion

### ISSUE THREAD

**Issue by AuTHeNTiiiX** [ioBroker/ioBroker.sonos#178]
**Describe the bug** 
Hallo habe heute mal den Datenpunkt Favorites Set angeschaut doch entweder er funktioniert nicht oder ich habe irgendwas übersehen, denn wenn ich was eintrage wird dieser auch richtig aktualisiert doch es passiert gar nichts bitte um Hilfe !

**Expected behavior**  
Ausgewählte Favoriten Playlist wird abgespielt

**Versions:**  
Adapter 2.2.3
Node.js: v16.18.0
NPM: 8.19.2

**Comment by Apollon77** [comment]
Bitte Loglevel der Instanz auf Debug stellen und log posten wenn Du das setzt

**Comment by AuTHeNTiiiX** [comment]
Jetzt gehts habe beim Datenpunkt setzen immer bestätigt angekreuzt wenn ich einfach nur auf Wert setzen klicke geht es👍

**Comment by Apollon77** [comment]
Naja "Bestätigt gesetzt" ist NIEMALS ein Kommando ...
