### ISSUE TITLE
Feature Request: Zufallswiedergabe

### ISSUE THREAD

**Issue by BramTown** [ioBroker/ioBroker.sonos#18]
Sofern dies über die API unterstützt wird, wäre die Erweiterung des SONOS Adapters um die Funktion "Zufallswiedergabe von Playlisten ein/auschalten" interessant

**Comment by Baenker** [comment]
Das würde ich mir auch wünschen... Wird an diesem Adapter noch gearbeitet?

**Comment by Apollon77** [comment]
Wir versuchen an allen > 100 Adaptern zu arbeiten. Unterstützung ist immer willkommen, ansonsten so wie es die Zeit - und die Geräteverfügbarkeit - zulässt

**Comment by Baenker** [comment]
War nur eine Frage. und nicht Böse gemeint. Es ist halt nur gut zu wissen wie es aussieht und ob man dann ggf sich andere Möglichkeiten suchen muss um das umzusetzen was man wil. In meinen Fall Wecken per Musik. Und dort ist es halt ohne Shuffle unsinnig. Wenn ich Ahnung hätte würde ich gerne helfen. Leider habe ich davon keine. Wie gesagt war micht böse gemeint.

**Comment by Apollon77** [comment]
Habe ich auch nicht böse aufgefasst ... alles gut.

**Comment by BramTown** [comment]
Die nachfrage war in so fern berechteit, denke ich, da in meinen bedien Requestst seit August keine Reaktion erfolgte, ich ging ehrlich gesagt auch davon aus, dass die Weiterentwicklung an dem SONOS Adapter tot sei ...

Ich bin leider auch kein Entwickler, stehe aber für Tests, Rückmeldungen und HowTo`s gern zur Verfügung

**Comment by Baenker** [comment]
Dieser Punkt kann auf gelöst gesetzt werden. Mit der aktuellen Version ist Shuffle möglich. Gerade getestet.

Vielen vielen Dank an @GermanBluefox. Kann ich per Paypal Dir eine Spende zukommen lassen?

**Comment by GermanBluefox** [comment]
@Baenker Natürlich geht es mit paypal: https://www.paypal.me/ioBrokerService
