### ISSUE TITLE
Status der Player werden nicht aktualisiert nach Starten der Radio-Wiedergabe über Alexa - Sonos App zeigt es aber richtig an #177

### ISSUE THREAD

**Issue by marian-t-web-de** [ioBroker/ioBroker.sonos#195]
**Describe the bug**  
Status der Player werden nicht aktualisiert nach Starten der Radio-Wiedergabe über Alexa - Sonos App zeigt es aber richtig an (siehe #177 ungelöst und geschlossen/staled)

**To Reproduce**  
1. Go to Sonos app
2. Click on Play
3. Check Statepoints "State" and "state_simple" in iObroker Sonos Object  - nothing is changed: state is still 'stop', state_simple 'false'
4. It is not correct/error

**Expected behavior**  
The states above have to be chenged depended of Sonos play / stop modus

**Versions:**  
 - Adapter version: <adapter-version>

**Versions:**  
 - Adapter version: Sonos 2.3.1

*Plattform
linux
Betriebssystem
linux
Architektur
arm
CPUs
4
Geschwindigkeit
1500 MHz
Modell
ARMv7 Processor rev 3 (v7l)
RAM
3.75 GB
System-Betriebszeit
49 T. 11:54:59
Node.js
v16.19.1 (Es gibt eine neuere Version: v16.20.0 - Empfohlene Version v18.16.0)
time
1684180018014
timeOffset
-120
Anzahl der Adapter
473
NPM
9.5.1
Datenträgergröße
28.14 GB
freier Festplattenspeicher
20.29 GB
Betriebszeit
13:15:46
Aktive Instanzen
24
Weg
/opt/iobroker/
Hostname
raspberrypi*Screenshots & Logfiles**  
it happens nothing

Remark:
The correct recognizing of sonos status is needed to set MediaPlayer status in (iObroker)-Lovelace

**Comment by Koalabaer** [comment]
+1

**Comment by marian-t-web-de** [comment]
This bug was found already by foxriver76 on Sep. 22, 2023 - still waiting for solution

**Comment by Apollon77** [comment]
duplicate #177

**Comment by Apollon77** [comment]
#177 is still open

The problem is that the log do not show anything being reported, so it is not an obvious fix.

I personally do not own any Sonos, foxriver76 also not. Means that we need such a device and time or another developer need to dig into this topic very deep.

Sorry, but I do not have any fast solution.

**Comment by marian-t-web-de** [comment]
For the future, to avoid misunderstandings, it would be better to comment the issues closing  instead keeping them for weeks open and close with no comment.
Ist a pitty nobody can solve it.

**Comment by Apollon77** [comment]
I added a comment as I closed it ... that it is a duplicate
