### ISSUE TITLE
Sonos adapter issues parsing errors for cover_png filling up the log with binary dumps

### ISSUE THREAD

**Issue by vuko** [ioBroker/ioBroker.sonos#196]
**Describe the bug**  
In unknown frequency the sonos adapter is trying to update the cover_png images. Every time the log is filled up with several thousands of lines with binary data starting with...

2023-07-16 18:06:13.513  - ^[[31merror^[[39m: Parsing error on getStates("io.sonos.0.root.192_168_0_8.cover_png"), returning "null" for "����^@^PJFIF^@^A^A^@^@^A^@^A^@^@��^@�^@^C^B^B...
...
B`�": Unexpected token � in JSON at position 0

The new written files for cover_png are working and are here, seems that somewhere is some rest of the old code trying to parse the image as an JSON.

**To Reproduce**  
1. Install Sonos adapter
2. Add Sonos device
3. Start adapter, log is filled up frequently

**Expected behavior**  
A possibility to hide this from the log, if the error does not become fixed. As it is an error, even the log level settings do not help either

**Versions:**  
 - Adapter version: 2.3.1
 - JS-Controller version: 5.0.8
 - Node version: 16.17.0
 - Operating system: OSX

**Comment by Apollon77** [comment]
Can you please post a full debug log of such a case? Only this one log line does not help too much because no idea where it comes from

**Comment by vuko** [comment]
Thanks for your reply, there was no prefix or previous log entries which allowed to see the origin, just this entry with kilobytes of binary data in the log. 

I now updated to node 18.17.0 and that solved the issue, so it seems some internal code of the sonos adapter, which needs node 18...
