### ISSUE TITLE
Beim Radio abspielen und dann TTS bleibt sayit.0.tts.mp3 stehen.

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.sonos#2]
Klappt bei euch Radiosender über Sonos hören, Radio stoppt, Ansage über Sayit läuft, Radio läuft weiter?

Bei mir funktioniert alles soweit, jedoch läuft der Radiostream nicht mehr weiter und in der App bleibts "sayit.0.tts.mp3" drin stehen.

http://forum.iobroker.org/viewtopic.php?f=20&t=511&start=40#p10915

**Comment by simpixo** [comment]
Ja das gleiche Problem habe ich auch. Und suche händeringend nach einer Lösung

**Comment by Marty56** [comment]
Habe ein ähnliches Problem. Dabei werden ohne das ich ein Radio benutzt unter irgendwelchen Umständen ein lange Liste von sayit.0.tts.mp3 in "Sonos Liste" eingetragen. Gleichzeitig steht die Sonos Lautstärke auf 0 und stellt sich immer wieder auf 0 zurück, wenn ich sie manuell verstelle.

**Comment by peterbaumert** [comment]
Gibt es hier schon etwas neues? Der Adapter ist so cool und das würde ihn einfach noch besser machen :)
