### ISSUE TITLE
v2.3.2 - Eintrag in Datenpunkt „current_cover“

### ISSUE THREAD

**Issue by ofri2607** [ioBroker/ioBroker.sonos#203]
**Describe the bug**  
Nach Update von v2.3.1 auf v2.3.2 steht im Datenpunkt „current_cover“ folgenden Eintrag: /files/sonos//opt/iobroker/iobroker-data/sonosCache/f6d5a1c06d8a5c1f0a908f1bdec205c4

Ich habe drei Lautsprecher (1x Sonos und 2x Symfonisk) eingetragen und in „current_cover“ steht bei allen drei der exakt gleiche, o.a. Eintrag. Testweise den Sonos-Lautsprecher aus der Liste gelöscht und dann wieder eingefügt. Der Eintrag im Datenpunkt „current_cover“ war wieder der Gleiche.

**Versions:**  
 - Adapter version: 2.3.2
 - JS-Controller version: 4.0.24
 - Node version: 18.17.1
 - Operating system: Bullseye

**Comment by foxriver76** [comment]
Kannst du mir evtl. das File bereitstellen, dass unter `/opt/iobroker/iobroker-data/sonosCache/f6d5a1c06d8a5c1f0a908f1bdec205c4` auf der Platte liegt?

**Comment by foxriver76** [comment]
Und bitte auch nochmal von GitHub aktualisieren, Dateiendung wird nun hinzugefügt

**Comment by ofri2607** [comment]
Den Filetyp .htm kann ich leider hier nicht hochladen, probiere bitte mal ob es hier downloaden kannst - https://1drv.ms/u/s!AgvOJNo13Kozg885jCO_FSk_9kdMtg?e=HSsMEj
Aktualisierung mache ich dann gleich und melde mich wieder.

**Comment by ofri2607** [comment]
Aktualisierung durchgeführt - jetzt steht folgendes im Datenpunkt: /sonos/coverImage/192_168_178_65.jpg.jpg
Aber positiv unter Dateien und auch beim Anklicken in der Vorschau wird ein Bild angezeigt :-)
![image](https://github.com/ioBroker/ioBroker.sonos/assets/123111495/4dbb7fdb-7986-462b-af7e-604327b87447)

**Comment by foxriver76** [comment]
öh okay ich schaue nochmal woher jetzt die doppelte dateiendung kommt

**Comment by foxriver76** [comment]
gerne nochmal upgraden

**Comment by ofri2607** [comment]
Sehr gerne.
Eines habe ich jetzt leider doch noch entdeckt; habe ja testweise auf einen anderen Sender "kronehit" geschalten (siehe oben), da hat er das Bild auch sauber aktualisiert, jedoch jetzt beim Zurückschalten auf den ursprünglichen Sender bleibt das Bild vom vorhergehend, (aktualisiert den Datenpunkt nicht)
siehe:
![image](https://github.com/ioBroker/ioBroker.sonos/assets/123111495/d36a3775-5dfb-48be-b440-e0b53fb0d342)
Eigentlich sollte da jetzt wieder das obige Bild von OE3 sein - in der Sonos-App selbst wird es korrekt angezeigt.
