### ISSUE TITLE
Warning "State [...].queue_html has no existing object

### ISSUE THREAD

**Issue by a-i-ks** [ioBroker/ioBroker.sonos#209]
Since updating to the latest JS-controller version I get the following warning in the log file with a high frequency.

`State "sonos.0.root.192_168_178_116.queue_html" has no existing object, this might lead to an error in future versions`

**Screenshots & Logfiles**  
![image](https://github.com/ioBroker/ioBroker.sonos/assets/6121974/f7357f8a-8db4-4a4e-9f9e-3f56e01d5d44)

**Versions:**  
 - Adapter version: v2.3.1
 - JS-Controller version: 5.0.12
 - Node version: v18.16.0
 - Operating system: Debian GNU/Linux 11 (bullseye)

**Comment by a-i-ks** [comment]
These warnings also appear when I restart the adapter
![image](https://github.com/ioBroker/ioBroker.sonos/assets/6121974/9bb08870-5f7a-492e-ab9b-4672f41c0eb6)

**Comment by justr1** [comment]
I had this once too and I think I solved it by stopping the instance, deleting the complete sonos.0.root object tree and restarting the instance.
It looks to me like newly needed objects are not always created correctly, except when the complete object tree is recreated.

**Comment by a-i-ks** [comment]
Thanks, this workaround fixed it for now.

**Comment by Feuer-sturm** [comment]
@a-i-ks You can close the issue if the warnings are not available any more after the states were created new.

**Comment by a-i-ks** [comment]
@Feuer-sturm I had left the ticket open, because the problem was only fixed by a workaround (deleting the object root). The actual root cause of this issue will still be there. That's why I would have the status of the issue decided by one of the main contributors to the repo.
