### ISSUE TITLE
uncaught exception: mime.lookup is not a function

### ISSUE THREAD

**Issue by pr0j3ctx** [ioBroker/ioBroker.sonos#23]
Hello.

Each time I open the Web-Adapter  I get this entrys in my log.

> sonos.0 | 2017-10-04 14:35:17.205 | info | http sonos server listening on port 8080
> -- | -- | -- | --
> sonos.0 | 2017-10-04 14:35:17.166 | info | starting. Version 1.6.2 in /opt/iobroker/node_modules/iobroker.sonos, node: v4.8.4
> sonos.0 | 2017-10-04 14:34:46.475 | info | terminating
> sonos.0 | 2017-10-04 14:34:46.472 | info | terminating
> sonos.0 | 2017-10-04 14:34:46.472 | error | at FSReqWrap.oncomplete (fs.js:82:15)
> sonos.0 | 2017-10-04 14:34:46.472 | error | at /opt/iobroker/node_modules/iobroker.sonos/node_modules/node-static/lib/node-static.js:64:22
> sonos.0 | 2017-10-04 14:34:46.472 | error | at Server.respond (/opt/iobroker/node_modules/iobroker.sonos/node_modules/node-static/lib/node-static.js:348:28)
> sonos.0 | 2017-10-04 14:34:46.472 | error | TypeError: mime.lookup is not a function
> sonos.0 | 2017-10-04 14:34:46.471 | error | uncaught exception: mime.lookup is not a function
> sonos.0 | 2017-10-04 14:24:04.985 | info | http sonos server listening on port 8080
> sonos.0 | 2017-10-04 14:24:04.926 | info | starting. Version 1.6.2 in /opt/iobroker/node_modules/iobroker.sonos, node: v4.8.4

Greats
pr0

**Comment by Apollon77** [comment]
Welche js-controller-Version ist installiert? irgendwie ist hier scheinbar "mime" in 2.x installiert worden was Kompatibilität bricht. Die js-controller 1.2.1 hatte das gestern abend bis heute mittag mal kurz diesen fehler

**Comment by pr0j3ctx** [comment]
Hi.

Installiert ist folgendes:
iobroker.js-controller@1.1.3 /opt/iobroker/node_modules/iobroker.js-controller

Gruß
pr0

**Comment by Apollon77** [comment]
Kannst Du bitte mal Sonos Adapter neu installieren ?!

**Comment by pr0j3ctx** [comment]
Das ändert leider nichts. Gleiches verhalten.

**Comment by Apollon77** [comment]
Irgendwoher hast Du ein mime 2.x bekommen und das knallt jetzt. DIe Frage ist: woher. Der Sonos-Adapter hat das nicht.
Am besten lösche mal node_modules/mime und installiere adapter neu

**Comment by pr0j3ctx** [comment]
Also ich habe nochmal alles abgesucht. Ich bin mit dem npm noch nicht sehr vertraut. Aber für mich sieht es so aus, als ob gar kein mime Modul installiert ist.

**Comment by pr0j3ctx** [comment]
Sorry, das Problem war ich. Beim neuinstallieren habe ich nur die Instanz gelöscht und nicht den Adapter. Jetzt läuft alles.

Danke!
