### ISSUE TITLE
Reminder - Touch Elemente und Sleeptimer

### ISSUE THREAD

**Issue by MMeinhardt1** [ioBroker/ioBroker.sonos#236]
Hi,

gibt es hier noch jemanden der diesen Adapter weiterentwickelt oder wird der aktuelle Stand bleiben 🤔

Zur Erinnerung [#66](https://github.com/ioBroker/ioBroker.sonos/issues/66 )

Vielen Dank und ein schönes Wochenende

**Comment by Apollon77** [comment]
Duplicate issues eröffnen helfennicht wirklich wenn scheinbar kein verfügbarer Entwickler Sonos Geräte hat
