### ISSUE TITLE
State/state_simple nicht korrekt.

### ISSUE THREAD

**Issue by juliawf** [ioBroker/ioBroker.sonos#25]
Hallo, super Plugin! Habe damit innerhalb kürzeste Zeit einiges auf die Beine gestellt.
Was mir auffiel, ist das „state“ und „state_simple“ bei mir nicht korrekt angezeigt werden, wenn ich über SONOS App Gruppen bilde, dann ein oder mehrere Lautsprecher aus der Gruppe rausnehme, werden die beide Größen nicht bei allen Lautsprechern aktualisiert.
Ist das nur bei mir so? oder kann ich was dagegen mache?
Gruß Waleri

**Comment by pascal1503** [comment]
habe das gleiche Problem

**Comment by Makamp94** [comment]
Gleiches Problem bei mir. 
Nur ein Neustart des Adapters hilft.
Gibt es schon Lösungen oder Ideen?
lg Marco
