### ISSUE TITLE
Txt to Speech adapter is locking Sonos if text is short

### ISSUE THREAD

**Issue by Marty56** [ioBroker/ioBroker.sonos#27]
If the text which should be played by the Text to speech adapter using Sonos is too short (about 3-5 sec) then Sonos does not play the corresponding output. Further it refuses to play further text to speech commands and also any mp3 sounds.
This kind of "lock" state can only be left by hitting play in the Sonos App and deleting the playlist.

Workaround: test length of spoken text and add some dummy text if text is too short.
In my tests 20 characters seem to be about minimum text length.

My test setup is a Sonos Play and a Sonos Playbar. I have conducted the tests on the Playbar.

To reproduce try playing the text "hallo" which causes this state.
In contrast "hallo! Schönes Wetter heute!" does not fail.

**Comment by Apollon77** [comment]
When you start sonos in debug mode and compare the outputs for both different texts, is there a difference?

**Comment by Marty56** [comment]
I have no clue how to start the songs adapter in debug mode.
If this is working by selecting the appropriate log level then I am not able to this because I am running admin 3.1.5 which has a bug not permitting the change of the log level.

I could resume the test if this bug in admin is fixed.

**Comment by Apollon77** [comment]
Update Admin. Should be fixed in the meantime

**Comment by Marty56** [comment]
Bad advise. I updated admin and now I have no access to the webUI anymore.

**Comment by Apollon77** [comment]
Should not happen. Is admin adapter running? Restart tried? iobroker start admin ?!

**Comment by Marty56** [comment]
I have managed to restore the admin and can now provide the requested log.
I ran two test.

1. with long text: working fine
2. with short text working only the first time, then entering the "lock" state and second time not working again.
[sonos.log](https://github.com/ioBroker/ioBroker.sonos/files/1692783/sonos.log)
