### ISSUE TITLE
Sonos Adapter startet nach setzen von favorites_set

### ISSUE THREAD

**Issue by Homoran** [ioBroker/ioBroker.sonos#3]
Quelle im Forum:
http://forum.iobroker.org/viewtopic.php?f=22&p=11292#p11292

> habe den Fehler gefunden. Er ist in dem Adapter und zwar in Sonos.js versteckt.
> Um Ihn zu beheben muss in Zeilen 76 und 77
> "val: val" durch "val: state.val" ersetzt werden. Die Variable val kennt das Skript zu Recht nicht.

**Comment by GermanBluefox** [comment]
Fixed: https://github.com/ioBroker/ioBroker.sonos/commit/d75fb68503f43b7b35e531c6da2e2a34c4050fa3
