### ISSUE TITLE
after update to 1.7.2, sayit "doorbell script" doesn't work anymore

### ISSUE THREAD

**Issue by Qlink84** [ioBroker/ioBroker.sonos#30]
here is the error log:
`host.iobroker	2018-07-23 08:24:37.347	error	instance system.adapter.sonos.0 terminated with code 0 (OK)
Caught	2018-07-23 08:24:37.347	error	by controller[0]: at Timer.listOnTimeout (timers.js:290:5)
Caught	2018-07-23 08:24:37.347	error	by controller[0]: at tryOnTimeout (timers.js:323:5)
Caught	2018-07-23 08:24:37.347	error	by controller[0]: at ontimeout (timers.js:508:15)
Caught	2018-07-23 08:24:37.347	error	by controller[0]: at Timeout.playOnSonos [as _onTimeout] (C:\ioBroker\node_modules\iobroker.sonos\main.js:987:9)
Caught	2018-07-23 08:24:37.347	error	by controller[0]: at fadeOut (C:\ioBroker\node_modules\iobroker.sonos\main.js:805:20)
Caught	2018-07-23 08:24:37.347	error	by controller[0]: TypeError: Cannot create property 'actual' on boolean 'false'
sonos.0	2018-07-23 08:24:37.299	info	terminating
sonos.0	2018-07-23 08:24:37.299	error	at Timer.listOnTimeout (timers.js:290:5)
sonos.0	2018-07-23 08:24:37.299	error	at tryOnTimeout (timers.js:323:5)
sonos.0	2018-07-23 08:24:37.299	error	at ontimeout (timers.js:508:15)
sonos.0	2018-07-23 08:24:37.299	error	at Timeout.playOnSonos [as _onTimeout] (C:\ioBroker\node_modules\iobroker.sonos\main.js:987:9)
sonos.0	2018-07-23 08:24:37.299	error	at fadeOut (C:\ioBroker\node_modules\iobroker.sonos\main.js:805:20)
sonos.0	2018-07-23 08:24:37.299	error	TypeError: Cannot create property 'actual' on boolean 'false'
sonos.0	2018-07-23 08:24:37.299	error	uncaught exception: Cannot create property 'actual' on boolean 'false'`

here is  the doorbell script:
`var vol ="sayit.0.tts.volume";

function esklingelt() {
    var idSonosfav = getState("sonos.0.root.192_168_30_17.favorites_set").val;                  //speichern des aktuellen Senders
    var idSonosplay = getState ("sonos.0.root.192_168_30_17.state_simple").val;                 //Status des Speakers
    if (idSonosplay) {                                                                           //Wenn Radio läuft
        sendTo('sonos', 'send', '50;http://192.168.30.9:8082/sayit.0/tts.userfiles/maus.mp3');  //Mp3 Ausgabe mit Lautstärke 60
        setState ("sonos.0.root.192_168_30_17.favorites_set", idSonosfav);                      //nach 23 Sekunden gespeicherten Favoriten Sender wieder stellen
        setStateDelayed ("sonos.0.root.192_168_30_17.state_simple", idSonosplay, 23000);        //nach 23 Sekunden wieder starten
    } else {                                                                                     //Wenn Radio nicht läuft
        sendTo('sonos', 'send', '50;http://192.168.30.9:8082/sayit.0/tts.userfiles/maus.mp3');  //Mp3 Ausgabe mit Lautstärke 60
    }
}

on({id: "hm-rpc.0.LEQ01xxxxx.1.PRESS_SHORT"/*Taster_Haustuer_Klingel.PRESS_SHORT*/, val: true}, esklingelt); //bei kurzem Tastendruck "esklingelt" aufrufen
on({id: "hm-rpc.0.LEQ01xxxxx.1.PRESS_LONG"/*Taster_Haustuer_Klingel.PRESS_LONG*/, val: true}, esklingelt);   //bei langem Tastendruck "esklingelt" aufrufen`

with older versions of sonos adapter the script is working fine ...

**Comment by iotathome** [comment]
Not fixed in 1.76. Seel also Bug #31.
