### ISSUE TITLE
1.7.4: still error in function fadeout

### ISSUE THREAD

**Issue by justr1** [ioBroker/ioBroker.sonos#31]
Reproduzierbar mit Sayit während Radio läuft:
`2018-08-03 08:18:36.621  - error: sonos.0 uncaught exception: Cannot create property 'actual' on boolean 'true'`
`2018-08-03 08:18:36.621  - error: sonos.0 TypeError: Cannot create property 'actual' on boolean 'true'`
`    at fadeOut (/Users/Shared/iobroker/node_modules/iobroker.sonos/main.js:805:20)`
`    at playOnSonos (/Users/Shared/iobroker/node_modules/iobroker.sonos/main.js:987:9)`
`    at Immediate.setImmediate [as _onImmediate] (/Users/Shared/iobroker/node_modules/iobroker.sonos/main.js:1067:40)`
`2018-08-03 08:18:36.622  - info: sonos.0 terminating`
Es scheint so, als ob in der Funktion fadeout der Fall (typeof options === 'boolean' && options === true) nicht korrekt berücksichtigt wäre.

`setState("sayit.0.tts.text", "Test");`
hat bei mir zuletzt mit Version 1.6.2 funktioniert.

**Comment by rossiniscarface** [comment]
Hab das gleiche gestern festgestellt. 
Hab als workaround mal fadein und fadout auf 0 gestellt.

**Comment by GermanBluefox** [comment]
Kann jemand github version testen?

**Comment by justr1** [comment]
Bei mir funktioniert die github-Version gut!
Vielen Dank!!!

**Comment by rossiniscarface** [comment]
Bei mir funktioniert das FadeIN/FadeOut nicht. Es kommt zwar jetzt keine Fehlermeldung, aber ist eines von den beiden gesetzt, dann passieren die merkwürdigsten Dinge. 
Bei FadeOut > 0 wird gar nichts von sayIt ausgegeben, und das sayIt Ankündigungsfile wird nicht gespielt sondern bleibt in der Liste.
Bei FadeIn > 0 wird zwar die Meldung ausgegeben, aber dann wird die Lautstärke auf 0 gesetzt und die Wiedergabe läuft quasi stumm.

**Comment by iotathome** [comment]
Die aktuelle GitHub Version (1.76) hat bei mir noch das oben beschriebene Problem (Cannot create property 'actual'... ).
Letzte funktionierende Version 1.62.

**Comment by iotathome** [comment]
Läuft! Danke!
