### ISSUE TITLE
Problem with SayIt

### ISSUE THREAD

**Issue by HoffmannOs** [ioBroker/ioBroker.sonos#35]
host.buanet-iobroker1 | 2018-10-23 13:48:58.824 | error | instance system.adapter.sonos.0 terminated with code 0 (OK)
-- | -- | -- | --
host.buanet-iobroker1 | 2018-10-23 13:48:58.823 | error | Caught  by controller[2]: (node:1852) UnhandledPromiseRejectionWarning:  Unhandled promise rejection (rejection id: 5): Error: Got status 500  when invoking /MediaRenderer/AVTransport/Control
host.buanet-iobroker1 | 2018-10-23 13:48:58.823 | error | Caught  by controller[2]: (node:1852) UnhandledPromiseRejectionWarning:  Unhandled promise rejection (rejection id: 4): Error: Got status 500  when invoking /MediaRenderer/AVTransport/Control
host.buanet-iobroker1 | 2018-10-23 13:48:58.823 | error | Caught  by controller[2]: (node:1852) UnhandledPromiseRejectionWarning:  Unhandled promise rejection (rejection id: 3): Error: Got status 500  when invoking /MediaRenderer/AVTransport/Control
host.buanet-iobroker1 | 2018-10-23 13:48:58.823 | error | Caught by controller[2]:   path: '/opt/iobroker/iobroker-data/sonosCache/tts1.mp3"/' }
host.buanet-iobroker1 | 2018-10-23 13:48:58.823 | error | Caught by controller[2]:   syscall: 'open',
host.buanet-iobroker1 | 2018-10-23 13:48:58.823 | error | Caught by controller[2]:   code: 'EISDIR',
host.buanet-iobroker1 | 2018-10-23 13:48:58.823 | error | Caught by controller[2]:   errno: -21,
host.buanet-iobroker1 | 2018-10-23 13:48:58.823 | error | Caught by controller[2]:     at Error (native)
host.buanet-iobroker1 | 2018-10-23 13:48:58.823 | error | Caught  by controller[2]: { Error: EISDIR: illegal operation on a directory,  open '/opt/iobroker/iobroker-data/sonosCache/tts1.mp3"/'
host.buanet-iobroker1 | 2018-10-23 13:48:58.823 | error | Caught by controller[2]:   path: '" "sayit.0.tts.mp3"/' }
host.buanet-iobroker1 | 2018-10-23 13:48:58.823 | error | Caught by controller[2]:   syscall: 'open',
host.buanet-iobroker1 | 2018-10-23 13:48:58.823 | error | Caught by controller[2]:   code: 'ENOENT',
host.buanet-iobroker1 | 2018-10-23 13:48:58.823 | error | Caught by controller[2]:   errno: -2,
host.buanet-iobroker1 | 2018-10-23 13:48:58.823 | error | Caught by controller[2]:     at Error (native)
host.buanet-iobroker1 | 2018-10-23 13:48:58.823 | error | Caught by controller[2]: { Error: ENOENT: no such file or directory, open '" "sayit.0.tts.mp3"/'
host.buanet-iobroker1 | 2018-10-23 13:48:58.822 | error | Caught by controller[1]:   path: '/opt/iobroker/iobroker-data/sonosCache/tts0.mp3"/' }
host.buanet-iobroker1 | 2018-10-23 13:48:58.822 | error | Caught by controller[1]:   syscall: 'open',
host.buanet-iobroker1 | 2018-10-23 13:48:58.822 | error | Caught by controller[1]:   code: 'EISDIR',
host.buanet-iobroker1 | 2018-10-23 13:48:58.822 | error | Caught by controller[1]:   errno: -21,
host.buanet-iobroker1 | 2018-10-23 13:48:58.822 | error | Caught by controller[1]:     at Error (native)
host.buanet-iobroker1 | 2018-10-23 13:48:58.822 | error | Caught  by controller[1]: { Error: EISDIR: illegal operation on a directory,  open '/opt/iobroker/iobroker-data/sonosCache/tts0.mp3"/'
host.buanet-iobroker1 | 2018-10-23 13:48:58.822 | error | Caught by controller[0]:   path: '" "sayit.0.tts.mp3"/' }
host.buanet-iobroker1 | 2018-10-23 13:48:58.822 | error | Caught by controller[0]:   syscall: 'open',
host.buanet-iobroker1 | 2018-10-23 13:48:58.822 | error | Caught by controller[0]:   code: 'ENOENT',
host.buanet-iobroker1 | 2018-10-23 13:48:58.822 | error | Caught by controller[0]:   errno: -2,
host.buanet-iobroker1 | 2018-10-23 13:48:58.822 | error | Caught by controller[0]:     at Error (native)
host.buanet-iobroker1 | 2018-10-23 13:48:58.820 | error | Caught by controller[0]: { Error: ENOENT: no such file or directory, open '" "sayit.0.tts.mp3"/'

its Version 1.77

**Comment by daniel-lo** [comment]
Until about an hour ago I thought sayit had a problem. Now I figure the Sonos adapter is the culprit. Sayit renders everything fine and plays the steam but "now playing" stays fals and no output can be hear.
I also tried an Alexa command that should turn down the volume but it doesn't work either.

I have no errors in my log.

Before I downgrade from 1.77 please give some feedback .. whether there are known issues or not.
Any other advice is also much appreciated.

**Comment by daniel-lo** [comment]
I deleted all objects in sayit and sonos and now at least I have some reaction. My daughter tells me the music interrupts or sounds like fast forwarding .. but no voice is heard. Formerly I did have the effect that when the sonos was inactive and I triggered tts the music started playing but again no voice output.

**Comment by GermanBluefox** [comment]
Please test the newest version
