### ISSUE TITLE
Falscher Player wird angesprochen

### ISSUE THREAD

**Issue by LJSven** [ioBroker/ioBroker.sonos#40]
Ich habe das Problem, daß bei mir der falsche Player angesprochen wird. Es scheint daran zu liegen, daß unter "Member" der Falsche Raum steht. Wie kann ich das ändern?
![bildschirmfoto 2019-01-31 um 10 23 02](https://user-images.githubusercontent.com/8560588/52046543-3b576600-2547-11e9-9e52-f7021d2936fc.png)

**Comment by justr1** [comment]
Evtl. eine dumme Frage, aber bist du dir sicher, dass nicht einfach der channel-Name "Küche" falsch ist und es sich tatsächlich um die Box im Bad handelt? Ansonsten solltest du die Namen, die auch bei "members" genutzt werden, z.B. in der Sonos-App editieren können.

**Comment by BramTown** [comment]
Welche IP steht denn zudem im Feld "coordinator" und "memberChannels"?
die Angaben sollte identisch mit dem "Gerätenamen" sein (siehe oben direkt unter "root").
Ansonsten solltest Du die Angaben direkt in den Datenpunkten ändern können
