### ISSUE TITLE
Sonos and Ubuntu 18.04 LTS - No Titel Cover is displayed or Web Control possible

### ISSUE THREAD

**Issue by schmeckm** [ioBroker/ioBroker.sonos#43]
Hello everybody
I moved my Iobroker installation from a Raspberry PI to a Linux Mini Calculator (Beelink) with the OS Ubuntu LTS installed.  All adapters are working fine, but unfortunately not the Sonos adapter. In the object view as well as via the Sonos Web Controller, no covers are displayed.

Even if the link behind the "Cover URL" in the object view clicks it is displayed correctly, but in the browser you can not see a picture

For example, if I connect the Sonos to FHEM on the same machine, it works fine.

I suspect that it might have something to do with JSON, which may not work on Ubuntu or where you still need to install libaries / packages / permissions on em OS.

Does anyone have a tip?

Thanks for a help in advance

The OS installed is:

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

Markus

**Comment by gravidigit** [comment]
Same problem here. Which Adapter Version use you? On Iobroker Adapter lsit is 1.7.7. On Github 2.0.0.
