### ISSUE TITLE
startInstance system.adapter.sonos.0: required adapter "web" not found!

### ISSUE THREAD

**Issue by LJSven** [ioBroker/ioBroker.sonos#47]
Ich habe heute ein System Update gemacht auf js-controller 1.514 und node.js 10.16.0
Mein System ist Master Slave. Der Sonos Adapter lief in der Vergangenheit immer auf dem Slave. Lässt sich jetzt aber nicht mehr starten ->

startInstance system.adapter.sonos.0: required adapter "web" not found!

Gibt es da eine Lösung. 2x den Web Adapter zu installieren macht in meinen Augen keinen Sinn. Der Sonos Adapter läuft auf dem Slave um Resourcen zu sparen.

**Comment by Apollon77** [comment]
Was genau war vorher als js-controller drauf? versuch bitte mal eine zweite web instanz zu installieren aber nicht zu starten!

**Comment by LJSven** [comment]
Vorher lief 1.5.11 - jetzt habe ich eine 2. Webinstanz auf dem Slave installiert, aber nicht gestartet, dann geht der Sonos Adapter

**Comment by Apollon77** [comment]
duplicate of https://github.com/ioBroker/ioBroker.js-controller/issues/325
