### ISSUE TITLE
No update on states.

### ISSUE THREAD

**Issue by martinst87** [ioBroker/ioBroker.sonos#48]
Hi all, I´ve moved my ioBroker installation from an RaspberryPI to an Beeling BT3 pro with Debian. 
Now the sonos adapter is not getting any updates in its states except volume, favorites and members indicator. 

Current track, artist, cover, etc stays empty. I have this problem on Sonos Play 1 and Sonos Connect. 

Connection to Sonos device is basically working because play, pause, stop, etc buttons are working. Also volume state gets updated. 

I already tried to remove adapter and reinstall it - no changes
I´ve also tested to use different music source in Sonos device. Amazon Music, local music from my phone, music from plex server, nothing helped.

Tested with 1.7.7 from adapters page and 1.8 (I think this was from github)

Even in the log of iobroker I cannot find anything. 

Any idea? 
Thanks in advance.

**Comment by Hesse-Bub** [comment]
I have the same Problem with a new installtion, after researching, it seems for me, that some of the file operations are not working ...

I have already reported it here: https://github.com/ioBroker/ioBroker.sonos/issues/46

**Comment by helfi9999** [comment]
Hallo,
bei mir funktioniert es auch nicht mehr folgende DP's aktualisieren nicht mehr:
current_Duration, current_duration_s, current_elapsed, current_eleapsed_s, current_type, state, state_simple.
Intel Nuc mit Ubuntu und Nodejs 10.6.1 und Npm 6.9.0 Sonos Adapter 1.8.0

**Comment by aleks-83** [comment]
I have the same problem like the TO.

My system:
Win10
Node.js v10.16.3
NPM 6.11.2
JS 4.1.16

**Comment by Baenker** [comment]
Bitte Version 2.0 testen direkt von github die funktioniert

**Comment by martinst87** [comment]
> Bitte Version 2.0 testen direkt von github die funktioniert

Funktioniert jetzt.
Vielen Dank
