### ISSUE TITLE
Request: Update with node-sonos-http-api

### ISSUE THREAD

**Issue by Hesse-Bub** [ioBroker/ioBroker.sonos#49]
As the actual Sonos Adapter is making more and more trouble and the tts is not working for a long time. Maybe it would be good idea to create a new version based on the newer http api from jishy:

https://github.com/jishi/node-sonos-http-api

This would also be an option to include the newer sonos functions for the TV soundbars like night mode and improved speak sound.

Also the TTS functionality is working much better with this API

**Comment by Hesse-Bub** [comment]
not needed anymore, because @GermanBluefox fixed the problem and the adapter is working fine since Version 2.0

**Comment by t6a** [comment]
TTS still doesn't work
