### ISSUE TITLE
Sonos Default Port von 8083 auf 8080 ändern

### ISSUE THREAD

**Issue by ruhr70** [ioBroker/ioBroker.sonos#5]
[siehe: ioBroker Forum](http://forum.iobroker.net/viewtopic.php?f=20&p=22714#p22714)

In der Konfigurationsseite wird der Port 8032 für dei Webseite angezeigt. Wenn man diese bestätigt, funktioniert die Webseite nciht.

Wenn man die Default-Portnummer des Web-Adapters (8080) verwendet, funktioniert die Sonos-Steuerung per Webseite.

Der Default-Eintrag sollte von 8083 auf 8080 geändert werden.

**Comment by GermanBluefox** [comment]
Fixed.
