### ISSUE TITLE
[Feature Request] Status "isCurrentlyPlaying" (true/false)

### ISSUE THREAD

**Issue by Mic-M** [ioBroker/ioBroker.sonos#51]
It would be very useful having a state like "isCurrentlyPlaying", and set to true, if Sonos device is currently playing something, and set to false, if not playing anything (pause/stop).

Subscribing to states "sonos.0.....play", ".pause", ".stop" by the Javascript adapter and maintaining a state under "javascript.0...." does not work, if Sonos is controlled not via ioBroker (like through the app or by the buttons directly on a Sonos speaker, like Sonos One).
Therefore I would love to have this information within the Sonos adapter.

Thank you.
Other than that, awesome adapter, many thanks for the hard work! It works fantastic.

**Comment by Hesse-Bub** [comment]
There is already a state for this functionality: 'state_simple'

**Comment by Mic-M** [comment]
Thank you @Hesse-Bub for your reply. I am using adapter version 2.0.0 (and 1.7.7 before), and state 'state_simple' does not update if I activate 'pause' or 'play', so it does not show the current status.
