### ISSUE TITLE
TypeError: Cannot read property '$text' of undefined

### ISSUE THREAD

**Issue by chefkoch009** [ioBroker/ioBroker.sonos#57]
Adapter starts new again and again and always throws this error. 
`

host.iobroker | 2019-10-01 21:20:29.284 | error | instance system.adapter.sonos.0 terminated with code 0 (OK)
-- | -- | -- | --
Caught | 2019-10-01 21:20:29.284 | error | by controller[0]: at Immediate.setImmediate (/D/iobroker/node_modules/sonos-discovery/lib/helpers/streamer.js:12:18)
Caught | 2019-10-01 21:20:29.283 | error | by controller[0]: at Readable.push (_stream_readable.js:220:10)
Caught | 2019-10-01 21:20:29.283 | error | by controller[0]: at readableAddChunk (_stream_readable.js:265:11)
Caught | 2019-10-01 21:20:29.283 | error | by controller[0]: at addChunk (_stream_readable.js:284:12)
Caught | 2019-10-01 21:20:29.283 | error | by controller[0]: at Readable.emit (events.js:189:13)
Caught | 2019-10-01 21:20:29.283 | error | by controller[0]: at Readable.ondata (_stream_readable.js:689:20)
Caught | 2019-10-01 21:20:29.283 | error | by controller[0]: at SAXStream.write (/D/iobroker/node_modules/sax/lib/sax.js:239:18)
Caught | 2019-10-01 21:20:29.282 | error | by controller[0]: at SAXParser.write (/D/iobroker/node_modules/sax/lib/sax.js:1436:13)
Caught | 2019-10-01 21:20:29.282 | error | by controller[0]: at closeTag (/D/iobroker/node_modules/sax/lib/sax.js:889:7)
Caught | 2019-10-01 21:20:29.282 | error | by controller[0]: at emitNode (/D/iobroker/node_modules/sax/lib/sax.js:629:5)
Caught | 2019-10-01 21:20:29.282 | error | by controller[0]: at emit (/D/iobroker/node_modules/sax/lib/sax.js:624:35)
Caught | 2019-10-01 21:20:29.281 | error | by controller[0]: at SAXParser.me._parser.(anonymous function) [as onclosetag] (/D/iobroker/node_modules/sax/lib/sax.js:258:17)
Caught | 2019-10-01 21:20:29.281 | error | by controller[0]: at SAXStream.emit (events.js:189:13)
Caught | 2019-10-01 21:20:29.281 | error | by controller[0]: at SAXStream.onCloseTag (/D/iobroker/node_modules/xml-flow/lib/xml-flow.js:131:15)
Caught | 2019-10-01 21:20:29.280 | error | by controller[0]: at EventEmitter.emit (events.js:189:13)
Caught | 2019-10-01 21:20:29.280 | error | by controller[0]: at EventEmitter.sax.on (/D/iobroker/node_modules/sonos-discovery/lib/models/Player.js:89:28)
Caught | 2019-10-01 21:20:29.278 | error | by controller[0]: TypeError: Cannot read property '$text' of undefined
sonos.0 | 2019-10-01 21:20:29.112 | info | terminating

`

**Comment by GermanBluefox** [comment]
Version?

**Comment by Guenda85** [comment]
Same issue; Version 1.7.7


2019-11-08 10:43:10.339 - error: sonos.0 TypeError: Cannot read property '$text' of undefined
--
at EventEmitter.sax.on (/opt/iobroker/node_modules/sonos-discovery/lib/models/Player.js:89:28)
at emitOne (events.js:116:13)
at EventEmitter.emit (events.js:211:7)
at SAXStream.onCloseTag (/opt/iobroker/node_modules/xml-flow/lib/xml-flow.js:131:15)
at emitOne (events.js:116:13)
at SAXStream.emit (events.js:211:7)
at SAXParser.me._parser.(anonymous function) [as onclosetag] (/opt/iobroker/node_modules/sax/lib/sax.js:258:17)
at emit (/opt/iobroker/node_modules/sax/lib/sax.js:624:35)
at emitNode (/opt/iobroker/node_modules/sax/lib/sax.js:629:5)
at closeTag (/opt/iobroker/node_modules/sax/lib/sax.js:889:7)
at SAXParser.write (/opt/iobroker/node_modules/sax/lib/sax.js:1436:13)
at SAXStream.write (/opt/iobroker/node_modules/sax/lib/sax.js:239:18)
at Readable.ondata (_stream_readable.js:639:20)
at emitOne (events.js:116:13)
at Readable.emit (events.js:211:7)
at addChunk (_stream_readable.js:263:12)
2019-11-08 10:43:10.340 - info: sonos.0 terminating

**Comment by Apollon77** [comment]
Please reopen issue here https://github.com/jishi/node-sonos-discovery/issues because is an issue of the library andf not iobroker adapter.

**Comment by Guenda85** [comment]
https://github.com/jishi/node-sonos-discovery/issues/113

**Comment by jishi** [comment]
This software is using an outdated version of sonos-discovery. You need to update it to remove this error.

**Comment by GermanBluefox** [comment]
IN Version 2.0.1 is the new version used
