### ISSUE TITLE
error Caught by controller[0]: '/opt/iobroker/iobroker-data/sonosCache/86e1252ff62242c0de6a8c11e700cbfd'

### ISSUE THREAD

**Issue by helfi9999** [ioBroker/ioBroker.sonos#59]
Hallo,
habe das Problem das dieser Fehler auftritt: host.intelnuc-GB-BACE-3160 2019-10-27 20:55:07.296 error Caught by controller[0]: path:
host.intelnuc-GB-BACE-3160 2019-10-27 20:55:07.296 error Caught by controller[0]: syscall: 'open',
host.intelnuc-GB-BACE-3160 2019-10-27 20:55:07.296 error Caught by controller[0]: code: 'ENOENT',
host.intelnuc-GB-BACE-3160 2019-10-27 20:55:07.296 error Caught by controller[0]: errno: -2,
host.intelnuc-GB-BACE-3160 2019-10-27 20:55:07.296 error Caught by controller[0]: { [Error: ENOENT: no such file or directory, open '/opt/iobroker/iobroker-data/sonosCache/86e1252ff62242c0de6a8c11e700cbfd']
sonos.0 2019-10-27 20:55:07.251 error uncaught exception: ENOENT: no such file or directory, open '/opt/iobroker/iobroker-data/sonosCache/86e1252ff62242c0de6a8c11e700cbfd'
Habe 2 Sonos Boxen der Fehler tritt nur bei 1 Box auf.

Hat vielleicht schon jemand so einen Fehler

**Comment by Apollon77** [comment]
Duplicate #50
