### ISSUE TITLE
SONOS "" not found

### ISSUE THREAD

**Issue by aleks-83** [ioBroker/ioBroker.sonos#60]
Hi,

when i try to control my sonos speakers with the adapter i get the answer 
`SONOS "" not found`
Doesnt matter with command I try.

```
2019-10-31 05:08:22.841 - info: sonos.0 (8376) try to control id sonos.0.root.10_0_0_50.play with {"val":true,"ack":false,"ts":1572494902839,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1571502439311}
2019-10-31 05:08:22.841 - warn: sonos.0 (8376) SONOS "" not found
```

Win 10
JS 2.0.38
Sonos 2.0.0
Web 2.4.8 (if necessary)

**Comment by Atomschorsch** [comment]
Check your speaker IPs. I had the same error in the log, and after deleting and reinstalling the SONOS adapter, I found out that my speakers have been found at another IP address. Maybe I should use static IP addresses for the speakers.

**Comment by aleks-83** [comment]
All my smart home devices are setup with static IPs in my router.
But thanks for the hint, anyway.
Maybe it's usefull for others.

**Comment by Jey-Cee** [comment]
Saw this issue (a lot messages) after installing the adapter with js-controller 3.

**Comment by x1n3f** [comment]
Hello, 
i had the same issue. Maybe it will help:
I have configured 3 Sonos loudspeakers in Sonos adapter at first. I had "SONOS "" not found" in the logs.

When I have increased the log level on SONOS adapter, everything was ok (connection, etc.)

I have all 3 loudspeakers grouped with the Sonos app. After I have configured only one of the speakers in IOBroker, then everything worked with ttx.

**Comment by ju2kr** [comment]
Hi guys, i get the same error...

```
2020-10-30 14:55:20.646 - info: sonos.0 (8635) try to control id sonos.0.root.192_168_20_18.play with {"val":true,"ack":false,"ts":1604066120643,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1604066119889}
2020-10-30 14:55:20.647 - warn: sonos.0 (8635) SONOS "" not found
```

I tried the following things:

- reinstall adapter
- check firewall 
- ping device successful from iobroker host

my env:
sonos 2.1.0
Has anybody an idea how to fix it?

**Comment by Chris-We** [comment]
Hi I have the same issue.
I'm porting my iobroker instance from an Raspberry Pi 4 to an Docker container on a Synology.
The instance on the raspi works still fine but on the Docker instance I get the message:
`(10287) try to control id sonos.0.root.192_168_1_25.group_muted with {"val":false,"ack":false,"ts":1605312312742,"q":0,"from":"system.adapter.sonos.0","user":"system.user.admin","lc":1605312312683}
(10287) SONOS "" not found`

can somebody help me?

**Comment by Schorlewalker** [comment]
Hey, same problem here...
any solutions yet?
restart, log level does not do the trick... :-/
![image](https://user-images.githubusercontent.com/31313004/103245114-71820800-495f-11eb-9ff4-e2cf885b2673.png)
![image](https://user-images.githubusercontent.com/31313004/103245163-95454e00-495f-11eb-9205-160e966e31a3.png)
![image](https://user-images.githubusercontent.com/31313004/103245224-c0c83880-495f-11eb-884b-e496b89d053f.png)

runs on Docker

**Comment by Chris-We** [comment]
having the same issue.

**Comment by Chris-We** [comment]
So I found out that the error seems to have something to to with the firewall of my Synology Diskstation I'm running iobroker on as a docker container.
Unfortunately It seems to be not sufficient to open the ports mentioned at the Sonos support page: https://support.sonos.com/s/article/688?language=de

which ports is the adapter using?
