### ISSUE TITLE
[Request] data points for nightmode and speechenhancement 

### ISSUE THREAD

**Issue by Hesse-Bub** [ioBroker/ioBroker.sonos#62]
Can we add datapoints for nightmode (on/off) and speechenhancement (on/off).

This functions are available with all soundbars (playbar, playbase and beam) and used for the TV sound.

**Comment by MichaelMerkel** [comment]
yes please. that would be extremly usefull!

**Comment by Baenker** [comment]
Kann doch eigentlich geschlossen werden, da in #34 der gleiche Wunsch besteht oder?
