### ISSUE TITLE
Adapter-website is not working

### ISSUE THREAD

**Issue by ac-bra** [ioBroker/ioBroker.sonos#63]
Hi Team,

I installed 2.0.1 and the adapter-website is not working for me although iobroker shows me the symbol/lint to the adapter-website in the instances overview. I'm aware the website was removed with 2.0.0 but it seems in 2.0.1 she's back but not working. Also there is no port (8080) open on my system.
<img width="524" alt="Screenshot 2019-12-31 at 14 38 05" src="https://user-images.githubusercontent.com/58888538/71623214-337ec680-2bdb-11ea-8100-1adae945413d.png">
<img width="606" alt="Screenshot 2019-12-31 at 14 39 08" src="https://user-images.githubusercontent.com/58888538/71623228-5315ef00-2bdb-11ea-9573-caafce8ccb96.png">
<img width="1129" alt="Screenshot 2019-12-31 at 14 38 52" src="https://user-images.githubusercontent.com/58888538/71623229-5315ef00-2bdb-11ea-8979-db09ada81274.png">

**Comment by Apollon77** [comment]
Yes we need to remove the link. See Changelog please. That Webserver is no longer maintained by the developer of the library and so was removed in 2.0.0!
