### ISSUE TITLE
Adapter Dev Question: Extend this adapter or develop new adapter?

### ISSUE THREAD

**Issue by Mic-M** [ioBroker/ioBroker.sonos#67]
Hi Everyone,
Hi @GermanBluefox (owner of this adapter),

I consider converting https://github.com/Mic-M/iobroker.sonos-script into an adapter (plus adding additional features not covered by this script).
A question came up in the forum ([see post](https://forum.iobroker.net/post/419183)) whether it would make sense to integrate into the existing Sonos adapter.

My opinion: Keep it separated and have two adapters as a result:
1. The existing STABLE Sonos adapter, which provides all basic functionality required to control Sonos. 
2. New adapter named like "Sonos Extended" or "Sonos Control", which will require the existing adapter. The new adapter covers more user specific requests, greater Visualization support, and other fancy things not necessarily needed in the "basic/core" adapter.

My concern in merging into one adapter is:
* The more features / extensions being added to an adapter, the more risk that basic functionality breaks / no longer works.
* The API may change in June 2020 (see e.g. [engadget](https://www.engadget.com/2020-03-17-sonos-s2-app-operating-system-update-june.html) which then may require of core functionality. Having a separate adapter avoids potential side effects by additional features and developer can focus on potential API change implementation in the core adapter.
* Providing user specific features is not necessarily the scope of a "core" adapter if not used by the vast majority. 

Anyway, I am open to both options.

I look forward to your opinion, guys.
Thanks.

**Comment by Apollon77** [comment]
Also wenn ich das Skript so überfliege dann past das für mich alles in den Adapter rein und nicht als extra adapter. Man muss auch immer den Mehrwert vs Ressourcenbedarf für ne eigene zusätzliche Adapter instanz sehen ....

**Comment by GermanBluefox** [comment]
One adapter is better than two.
