### ISSUE TITLE
Error during startup since js-controller v3.1.x

### ISSUE THREAD

**Issue by BramTown** [ioBroker/ioBroker.sonos#68]
some log states to this error:
`

sonos.0 | 2020-05-11 22:00:07.942 | error | at processImmediate (internal/timers.js:456:21)
-- | -- | -- | --
sonos.0 | 2020-05-11 22:00:07.942 | error | at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5388:34)
sonos.0 | 2020-05-11 22:00:07.942 | error | at Adapter.emit (events.js:310:20)
sonos.0 | 2020-05-11 22:00:07.942 | error | at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.sonos/main.js:81:32)
sonos.0 | 2020-05-11 22:00:07.942 | error | at Player.pause (/opt/iobroker/node_modules/iobroker.sonos/node_modules/sonos-discovery/lib/models/Player.js:453:15)
sonos.0 | 2020-05-11 22:00:07.942 | error | at Object.invoke (/opt/iobroker/node_modules/iobroker.sonos/node_modules/sonos-discovery/lib/helpers/soap.js:99:10)
sonos.0 | 2020-05-11 22:00:07.942 | error | (1688) Error: Got status 500 when invoking /MediaRenderer/AVTransport/Control
sonos.0 | 2020-05-11 22:00:07.942 | error | (1688) unhandled promise rejection: Got status 500 when invoking /MediaRenderer/AVTransport/Control
Unhandled | 2020-05-11 22:00:07.942 | error | promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
sonos.0 | 2020-05-11 22:00:07.833 | error | at processImmediate (internal/timers.js:456:21)
sonos.0 | 2020-05-11 22:00:07.833 | error | at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5388:34)
sonos.0 | 2020-05-11 22:00:07.833 | error | at Adapter.emit (events.js:310:20)
sonos.0 | 2020-05-11 22:00:07.833 | error | at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.sonos/main.js:81:32)
sonos.0 | 2020-05-11 22:00:07.833 | error | at Player.pause (/opt/iobroker/node_modules/iobroker.sonos/node_modules/sonos-discovery/lib/models/Player.js:453:15)
sonos.0 | 2020-05-11 22:00:07.833 | error | at Object.invoke (/opt/iobroker/node_modules/iobroker.sonos/node_modules/sonos-discovery/lib/helpers/soap.js:99:10)
sonos.0 | 2020-05-11 22:00:07.833 | error | (1688) Error: Got status 500 when invoking /MediaRenderer/AVTransport/Control
sonos.0 | 2020-05-11 22:00:07.832 | error | (1688) unhandled promise rejection: Got status 500 when invoking /MediaRenderer/AVTransport/Control
Unhandled | 2020-05-11 22:00:07.829 | error | promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
host.debian | 2020-05-11 22:00:06.344 | info | instance system.adapter.sonos.0 started with pid 1688

`

**Comment by BramTown** [comment]
und nach dem Start kommt im Minutentakt folgender Fehler
`

sonos.0 | 2020-05-11 22:04:23.627 | error | (2394) Error: Got status 500 when invoking /MediaRenderer/AVTransport/Control at Object.invoke (/opt/iobroker/node_modules/iobroker.sonos/node_modules/sonos-discovery/lib/helpers/soap.js:99:10)
-- | -- | -- | --
sonos.0 | 2020-05-11 22:04:23.627 | error | (2394) unhandled promise rejection: Got status 500 when invoking /MediaRenderer/AVTransport/Control
sonos.0 | 2020-05-11 22:04:23.625 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
sonos.0 | 2020-05-11 22:04:23.623 | error | (2394) Error: Got status 500 when invoking /MediaRenderer/AVTransport/Control at Object.invoke (/opt/iobroker/node_modules/iobroker.sonos/node_modules/sonos-discovery/lib/helpers/soap.js:99:10)
sonos.0 | 2020-05-11 22:04:23.623 | error | (2394) unhandled promise rejection: Got status 500 when invoking /MediaRenderer/AVTransport/Control
sonos.0 | 2020-05-11 22:04:23.622 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().


`

**Comment by Apollon77** [comment]
This is an error 500 when communicating with Sonos/The device. Try a rebstart there please ... controller has nothing to do with this

**Comment by Apollon77** [comment]
But yes the crash shuld be prevented

**Comment by BramTown** [comment]
was kann ich tun?
solange ich auf js-controllerr v3.0.20 bleibe ist alles in Ordnung, keine Fehlermeldung.
Es wird auf jede Ansprache des Adapters auch korrekt reagiert.
Kaum aktualisiere ich auf js-controller v3.1.x ist reproduzierbar der Adapter nicht mehr auf grün zu bekommen .... kann ich mit weiteren Details oder Informationen helfen?

**Comment by Apollon77** [comment]
Ich habe null Idee wie sowas von dem Update des Controllers kommen kann.

**Comment by Apollon77** [comment]
mach ggf mal debug log an und lass sehen ob wir was sehen

**Comment by Apollon77** [comment]
could the be some part of the problem?
https://github.com/jishi/node-sonos-http-api/issues/741

**Comment by BramTown** [comment]
Moin Ingo,
vielen Dank für deine Recherche, ich werde die Punkte Stück für Stück abarbeiten und die Ergebnisse dann mitteilen.
Ich habe zwar keine Playbar und ich nutze auch nicht die "Pause" Funktion, allerdings habe ich andere SONOS Geräte mit HDMIarc oder spdif (Beam, Connect, ConnectAmp) und womöglich wird mit "Pause" auch nicht explizit "Pause" sondern "Musik Stop" oder "Gruppenauflösung" bezeichnet.

**Comment by BramTown** [comment]
Moin Ingo,
hast Du doch noch etwas am js-controller gefunden?
Ich habe eben alles aktualisiert und war total perplex, dass der Sonos Adapter ohne Fehler auf grün geht (und auch bleibt) und erst anschließend habe ich ebenso überrascht festgestellt, das der js-controller gar nicht auf die v3.1.4 sondern auf v3.2.0 aktualisiert wurde.

Aktuelles Fazit:
Die Kombination js-controller v3.0.x und v3.2.x scheint in Verbindung mit dem Sonos Adapter v2.0.1 zu funktionieren, lediglich - die v3.1.x machte bei mir Probleme

Vielen Dank für deine unermüdliche Arbeit!! 👍

**Comment by Apollon77** [comment]
Äääähhmm ... dann sag ich mal: WTF ;-)

Der js.controller ist auf Github jetzt auf 3.2. als Version gestellt, ansonsten sind darin KEINERLEI Änderungen zur 3.1.4 ...

Aber hey wenns tut super :-)

**Comment by BramTown** [comment]
Mitunter sollen ja auch Placebos heilen/helfen ;-)
ich kann es die nicht erklären, aber wie Du selber sagst, wenn es denn hilft :-)

**Comment by BramTown** [comment]
@Apollon77 
Ich doch schon wieder.... :-)
Der Adapter bliebt grün und die meisten Funktionen scheinen zu laufen, jedoch bekomme ich zusätzlich eine ganze reihe Fehlermeldungen ins LOG.

Gib gerne Laut, ob dies in ein neues Issue soll, oder ob das hier fortzuführen in Ordnung ist?!

`

sonos.0 | 2020-05-17 10:50:18.486 | error | at processImmediate (internal/timers.js:456:21)
-- | -- | -- | --
sonos.0 | 2020-05-17 10:50:18.486 | error | at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5396:34)
sonos.0 | 2020-05-17 10:50:18.486 | error | at Adapter.emit (events.js:310:20)
sonos.0 | 2020-05-17 10:50:18.486 | error | at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.sonos/main.js:187:25)
sonos.0 | 2020-05-17 10:50:18.486 | error | at attachTo (/opt/iobroker/node_modules/iobroker.sonos/main.js:924:12)
sonos.0 | 2020-05-17 10:50:18.486 | error | at Player.setAVTransport (/opt/iobroker/node_modules/iobroker.sonos/node_modules/sonos-discovery/lib/models/Player.js:727:15)
sonos.0 | 2020-05-17 10:50:18.486 | error | at Object.invoke (/opt/iobroker/node_modules/iobroker.sonos/node_modules/sonos-discovery/lib/helpers/soap.js:99:10)
sonos.0 | 2020-05-17 10:50:18.486 | error | (9932) Error: Got status 500 when invoking /MediaRenderer/AVTransport/Control
sonos.0 | 2020-05-17 10:50:18.485 | error | (9932) unhandled promise rejection: Got status 500 when invoking /MediaRenderer/AVTransport/Control
Unhandled | 2020-05-17 10:50:18.485 | error | promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
sonos.0 | 2020-05-17 10:50:18.477 | error | at processImmediate (internal/timers.js:456:21)
sonos.0 | 2020-05-17 10:50:18.477 | error | at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5396:34)
sonos.0 | 2020-05-17 10:50:18.477 | error | at Adapter.emit (events.js:310:20)
sonos.0 | 2020-05-17 10:50:18.477 | error | at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.sonos/main.js:187:25)
sonos.0 | 2020-05-17 10:50:18.477 | error | at attachTo (/opt/iobroker/node_modules/iobroker.sonos/main.js:924:12)
sonos.0 | 2020-05-17 10:50:18.477 | error | at Player.setAVTransport (/opt/iobroker/node_modules/iobroker.sonos/node_modules/sonos-discovery/lib/models/Player.js:727:15)
sonos.0 | 2020-05-17 10:50:18.477 | error | at Object.invoke (/opt/iobroker/node_modules/iobroker.sonos/node_modules/sonos-discovery/lib/helpers/soap.js:99:10)
sonos.0 | 2020-05-17 10:50:18.477 | error | (9932) Error: Got status 500 when invoking /MediaRenderer/AVTransport/Control
sonos.0 | 2020-05-17 10:50:18.477 | error | (9932) unhandled promise rejection: Got status 500 when invoking /MediaRenderer/AVTransport/Control
Unhandled | 2020-05-17 10:50:18.476 | error | promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
sonos.0 | 2020-05-17 10:50:18.464 | error | at processImmediate (internal/timers.js:456:21)
sonos.0 | 2020-05-17 10:50:18.464 | error | at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5396:34)
sonos.0 | 2020-05-17 10:50:18.464 | error | at Adapter.emit (events.js:310:20)
sonos.0 | 2020-05-17 10:50:18.464 | error | at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.sonos/main.js:187:25)
sonos.0 | 2020-05-17 10:50:18.464 | error | at attachTo (/opt/iobroker/node_modules/iobroker.sonos/main.js:924:12)
sonos.0 | 2020-05-17 10:50:18.464 | error | at Player.setAVTransport (/opt/iobroker/node_modules/iobroker.sonos/node_modules/sonos-discovery/lib/models/Player.js:727:15)
sonos.0 | 2020-05-17 10:50:18.464 | error | at Object.invoke (/opt/iobroker/node_modules/iobroker.sonos/node_modules/sonos-discovery/lib/helpers/soap.js:99:10)
sonos.0 | 2020-05-17 10:50:18.464 | error | (9932) Error: Got status 500 when invoking /MediaRenderer/AVTransport/Control
sonos.0 | 2020-05-17 10:50:18.464 | error | (9932) unhandled promise rejection: Got status 500 when invoking /MediaRenderer/AVTransport/Control
Unhandled | 2020-05-17 10:50:18.464 | error | promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
sonos.0 | 2020-05-17 10:50:18.463 | error | at processImmediate (internal/timers.js:456:21)
sonos.0 | 2020-05-17 10:50:18.463 | error | at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5396:34)
sonos.0 | 2020-05-17 10:50:18.463 | error | at Adapter.emit (events.js:310:20)
sonos.0 | 2020-05-17 10:50:18.463 | error | at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.sonos/main.js:187:25)
sonos.0 | 2020-05-17 10:50:18.463 | error | at attachTo (/opt/iobroker/node_modules/iobroker.sonos/main.js:924:12)
sonos.0 | 2020-05-17 10:50:18.463 | error | at Player.setAVTransport (/opt/iobroker/node_modules/iobroker.sonos/node_modules/sonos-discovery/lib/models/Player.js:727:15)
sonos.0 | 2020-05-17 10:50:18.463 | error | at Object.invoke (/opt/iobroker/node_modules/iobroker.sonos/node_modules/sonos-discovery/lib/helpers/soap.js:99:10)
sonos.0 | 2020-05-17 10:50:18.463 | error | (9932) Error: Got status 500 when invoking /MediaRenderer/AVTransport/Control
sonos.0 | 2020-05-17 10:50:18.462 | error | (9932) unhandled promise rejection: Got status 500 when invoking /MediaRenderer/AVTransport/Control
Unhandled | 2020-05-17 10:50:18.462 | error | promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
sonos.0 | 2020-05-17 10:50:18.451 | error | at processImmediate (internal/timers.js:456:21)
sonos.0 | 2020-05-17 10:50:18.451 | error | at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5396:34)
sonos.0 | 2020-05-17 10:50:18.451 | error | at Adapter.emit (events.js:310:20)
sonos.0 | 2020-05-17 10:50:18.451 | error | at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.sonos/main.js:187:25)
sonos.0 | 2020-05-17 10:50:18.451 | error | at attachTo (/opt/iobroker/node_modules/iobroker.sonos/main.js:924:12)
sonos.0 | 2020-05-17 10:50:18.451 | error | at Player.setAVTransport (/opt/iobroker/node_modules/iobroker.sonos/node_modules/sonos-discovery/lib/models/Player.js:727:15)
sonos.0 | 2020-05-17 10:50:18.451 | error | at Object.invoke (/opt/iobroker/node_modules/iobroker.sonos/node_modules/sonos-discovery/lib/helpers/soap.js:99:10)
sonos.0 | 2020-05-17 10:50:18.451 | error | (9932) Error: Got status 500 when invoking /MediaRenderer/AVTransport/Control
sonos.0 | 2020-05-17 10:50:18.451 | error | (9932) unhandled promise rejection: Got status 500 when invoking /MediaRenderer/AVTransport/Control
Unhandled | 2020-05-17 10:50:18.451 | error | promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
sonos.0 | 2020-05-17 10:50:18.443 | error | at processImmediate (internal/timers.js:456:21)
sonos.0 | 2020-05-17 10:50:18.443 | error | at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5396:34)
sonos.0 | 2020-05-17 10:50:18.443 | error | at Adapter.emit (events.js:310:20)
sonos.0 | 2020-05-17 10:50:18.443 | error | at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.sonos/main.js:187:25)
sonos.0 | 2020-05-17 10:50:18.443 | error | at attachTo (/opt/iobroker/node_modules/iobroker.sonos/main.js:924:12)
sonos.0 | 2020-05-17 10:50:18.443 | error | at Player.setAVTransport (/opt/iobroker/node_modules/iobroker.sonos/node_modules/sonos-discovery/lib/models/Player.js:727:15)
sonos.0 | 2020-05-17 10:50:18.443 | error | at Object.invoke (/opt/iobroker/node_modules/iobroker.sonos/node_modules/sonos-discovery/lib/helpers/soap.js:99:10)
sonos.0 | 2020-05-17 10:50:18.443 | error | (9932) Error: Got status 500 when invoking /MediaRenderer/AVTransport/Control
sonos.0 | 2020-05-17 10:50:18.442 | error | (9932) unhandled promise rejection: Got status 500 when invoking /MediaRenderer/AVTransport/Control
Unhandled | 2020-05-17 10:50:18.442 | error | promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
sonos.0 | 2020-05-17 10:50:18.429 | error | at processImmediate (internal/timers.js:456:21)
sonos.0 | 2020-05-17 10:50:18.429 | error | at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5396:34)
sonos.0 | 2020-05-17 10:50:18.429 | error | at Adapter.emit (events.js:310:20)
sonos.0 | 2020-05-17 10:50:18.429 | error | at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.sonos/main.js:187:25)
sonos.0 | 2020-05-17 10:50:18.429 | error | at attachTo (/opt/iobroker/node_modules/iobroker.sonos/main.js:924:12)
sonos.0 | 2020-05-17 10:50:18.429 | error | at Player.setAVTransport (/opt/iobroker/node_modules/iobroker.sonos/node_modules/sonos-discovery/lib/models/Player.js:727:15)
sonos.0 | 2020-05-17 10:50:18.429 | error | at Object.invoke (/opt/iobroker/node_modules/iobroker.sonos/node_modules/sonos-discovery/lib/helpers/soap.js:99:10)
sonos.0 | 2020-05-17 10:50:18.429 | error | (9932) Error: Got status 500 when invoking /MediaRenderer/AVTransport/Control
sonos.0 | 2020-05-17 10:50:18.429 | error | (9932) unhandled promise rejection: Got status 500 when invoking /MediaRenderer/AVTransport/Control
Unhandled | 2020-05-17 10:50:18.425 | error | promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().


`

**Comment by Apollon77** [comment]
Also wenn es aus dem "nichts" wieder auftaucht bin ich jetzt wirklich bei deiner Hardware und ideen wie in den Links oben. Sch bitte mal weiter und versuch mal EInstellungen zu ändern was Quellen angeht und so raszufinden was passieren muss das der Fehler kommt

**Comment by Apollon77** [comment]
Ist ja auch diesmla nicht "Pause" sondern setAVTransport...also eine andere Funktion

**Comment by DominikReber** [comment]
`

sonos.0 | 2020-12-27 22:12:51.557 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
-- | -- | -- | --
sonos.0 | 2020-12-27 22:12:51.557 | error | at runMicrotasks (<anonymous>)
sonos.0 | 2020-12-27 22:12:51.557 | error | at /opt/iobroker/node_modules/sonos-discovery/lib/NotificationListener.js:125:17
sonos.0 | 2020-12-27 22:12:51.557 | error | at NotificationListener.emit (events.js:314:20)
sonos.0 | 2020-12-27 22:12:51.557 | error | at NotificationListener.notificationHandler (/opt/iobroker/node_modules/sonos-discovery/lib/models/Player.js:363:20)
sonos.0 | 2020-12-27 22:12:51.557 | error | at SonosSystem.emit (events.js:314:20)
sonos.0 | 2020-12-27 22:12:51.557 | error | at SonosSystem.<anonymous> (/opt/iobroker/node_modules/iobroker.sonos/main.js:1940:9)
sonos.0 | 2020-12-27 22:12:51.557 | error | at processSonosEvents (/opt/iobroker/node_modules/iobroker.sonos/main.js:1679:28)
sonos.0 | 2020-12-27 22:12:51.557 | error | (20434) TypeError: Cannot read property 'getPlayerByUUID' of null
sonos.0 | 2020-12-27 22:12:51.557 | error | (20434) unhandled promise rejection: Cannot read property 'getPlayerByUUID' of null
Unhandled | 2020-12-27 22:12:51.556 | error | promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
sonos.0 | 2020-12-27 22:12:51.551 | error | (20434) Cannot loadQueue: TypeError: Cannot read property 'getPlayerByUUID' of null
sonos.0 | 2020-12-27 22:12:51.530 | info | (20434) terminating
sonos.0 | 2020-12-27 22:12:51.528 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
sonos.0 | 2020-12-27 22:12:51.528 | error | at runMicrotasks (<anonymous>)
sonos.0 | 2020-12-27 22:12:51.528 | error | at /opt/iobroker/node_modules/iobroker.sonos/lib/tts.js:163:57
sonos.0 | 2020-12-27 22:12:51.528 | error | at Player.trackSeek (/opt/iobroker/node_modules/sonos-discovery/lib/models/Player.js:552:15)
sonos.0 | 2020-12-27 22:12:51.528 | error | at Object.invoke (/opt/iobroker/node_modules/sonos-discovery/lib/helpers/soap.js:99:10)
sonos.0 | 2020-12-27 22:12:51.528 | error | (20434) Error: Got status 500 when invoking /MediaRenderer/AVTransport/Control
sonos.0 | 2020-12-27 22:12:51.528 | error | (20434) unhandled promise rejection: Got status 500 when invoking /MediaRenderer/AVTransport/Control
Unhandled | 2020-12-27 22:12:51.527 | error | promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled wit

`

Ich hab ähnliches...
