### ISSUE TITLE
2.1.0: Errors when using Sonos adapter in combination with Say.it-adapter

### ISSUE THREAD

**Issue by Superwuzy** [ioBroker/ioBroker.sonos#72]
The Sonos adapter is throwing 3 types of exceptions (not always but regularily) when trying to speak text:

1.

```
sonos.0 | 2020-05-31 20:34:13.390 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
-- | -- | -- | --
sonos.0 | 2020-05-31 20:34:13.390 | error | at runMicrotasks (<anonymous>)
sonos.0 | 2020-05-31 20:34:13.390 | error | at /opt/iobroker/node_modules/iobroker.sonos/lib/tts.js:163:57
sonos.0 | 2020-05-31 20:34:13.390 | error | at Player.trackSeek (/opt/iobroker/node_modules/sonos-discovery/lib/models/Player.js:552:15)
sonos.0 | 2020-05-31 20:34:13.390 | error | at Object.invoke (/opt/iobroker/node_modules/sonos-discovery/lib/helpers/soap.js:99:10)
sonos.0 | 2020-05-31 20:34:13.390 | error | (9040) Error: Got status 500 when invoking /MediaRenderer/AVTransport/Control
sonos.0 | 2020-05-31 20:34:13.390 | error | (9040) unhandled promise rejection: Got status 500 when invoking /MediaRenderer/AVTransport/Control
Unhandled | 2020-05-31 20:34:13.389 | error | promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
```

2. 

```
sonos.0 | 2020-05-31 20:36:57.183 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
-- | -- | -- | --
sonos.0 | 2020-05-31 20:36:57.183 | error | at /opt/iobroker/node_modules/sonos-discovery/lib/NotificationListener.js:125:17
sonos.0 | 2020-05-31 20:36:57.183 | error | at NotificationListener.emit (events.js:327:22)
sonos.0 | 2020-05-31 20:36:57.183 | error | at NotificationListener.notificationHandler (/opt/iobroker/node_modules/sonos-discovery/lib/models/Player.js:363:20)
sonos.0 | 2020-05-31 20:36:57.183 | error | at SonosSystem.emit (events.js:315:20)
sonos.0 | 2020-05-31 20:36:57.183 | error | at SonosSystem.<anonymous> (/opt/iobroker/node_modules/iobroker.sonos/main.js:1912:9)
sonos.0 | 2020-05-31 20:36:57.183 | error | at processSonosEvents (/opt/iobroker/node_modules/iobroker.sonos/main.js:1667:28)
sonos.0 | 2020-05-31 20:36:57.183 | error | (27265) TypeError: Cannot read property 'getPlayerByUUID' of null
sonos.0 | 2020-05-31 20:36:57.182 | error | (27265) unhandled promise rejection: Cannot read property 'getPlayerByUUID' of null
Unhandled | 2020-05-31 20:36:57.182 | error | promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch()
```

3.

```
sonos.0 | 2020-05-31 20:36:57.231 | error | at processTimers (internal/timers.js:492:7)
-- | -- | -- | --
sonos.0 | 2020-05-31 20:36:57.231 | error | at listOnTimeout (internal/timers.js:549:17)
sonos.0 | 2020-05-31 20:36:57.231 | error | at Timeout._onTimeout (/opt/iobroker/node_modules/sonos-discovery/lib/prototypes/Player/recalculateGroupVolume.js:30:17)
sonos.0 | 2020-05-31 20:36:57.231 | error | at SonosSystem.emit (events.js:315:20)
sonos.0 | 2020-05-31 20:36:57.231 | error | at SonosSystem.<anonymous> (/opt/iobroker/node_modules/iobroker.sonos/main.js:1907:9)
sonos.0 | 2020-05-31 20:36:57.231 | error | at processSonosEvents (/opt/iobroker/node_modules/iobroker.sonos/main.js:1615:35)
sonos.0 | 2020-05-31 20:36:57.231 | error | (27265) TypeError: Cannot read property 'players' of null
sonos.0 | 2020-05-31 20:36:57.230 | error | (27265) uncaught exception: Cannot read property 'players' of null
sonos.0 | 2020-05-31 20:36:57.219 | error | (27265) Cannot loadQueue: TypeError: Cannot read property 'getPlayerByUUID' of null
```

**Comment by Superwuzy** [comment]
When tryring to "say" something with the sayit-Adapter I'm getting an error:

`
sonos.0 | 2020-06-01 09:36:04.869 | error | at processTimers (internal/timers.js:492:7)
-- | -- | -- | --
sonos.0 | 2020-06-01 09:36:04.869 | error | at listOnTimeout (internal/timers.js:549:17)
sonos.0 | 2020-06-01 09:36:04.869 | error | at Timeout._onTimeout (/opt/iobroker/node_modules/sonos-discovery/lib/prototypes/Player/recalculateGroupVolume.js:30:17)
sonos.0 | 2020-06-01 09:36:04.869 | error | at SonosSystem.emit (events.js:315:20)
sonos.0 | 2020-06-01 09:36:04.869 | error | at SonosSystem.<anonymous> (/opt/iobroker/node_modules/iobroker.sonos/main.js:1907:9)
sonos.0 | 2020-06-01 09:36:04.869 | error | at processSonosEvents (/opt/iobroker/node_modules/iobroker.sonos/main.js:1615:35)
sonos.0 | 2020-06-01 09:36:04.869 | error | (20583) TypeError: Cannot read property 'players' of null
sonos.0 | 2020-06-01 09:36:04.868 | error | (20583) uncaught exception: Cannot read property 'players' of null
sonos.0 | 2020-06-01 09:36:04.787 | info | (20583) Terminated (NO_ERROR): Without reason
sonos.0 | 2020-06-01 09:36:04.786 | info | (20583) terminating
sonos.0 | 2020-06-01 09:36:04.772 | info | (20583) terminating
sonos.0 | 2020-06-01 09:36:04.771 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
sonos.0 | 2020-06-01 09:36:04.771 | error | at /opt/iobroker/node_modules/iobroker.sonos/lib/tts.js:163:57
sonos.0 | 2020-06-01 09:36:04.771 | error | at Player.trackSeek (/opt/iobroker/node_modules/sonos-discovery/lib/models/Player.js:552:15)
sonos.0 | 2020-06-01 09:36:04.771 | error | at Object.invoke (/opt/iobroker/node_modules/sonos-discovery/lib/helpers/soap.js:99:10)
sonos.0 | 2020-06-01 09:36:04.771 | error | (20583) Error: Got status 500 when invoking /MediaRenderer/AVTransport/Control
sonos.0 | 2020-06-01 09:36:04.770 | error | (20583) unhandled promise rejection: Got status 500 when invoking /MediaRenderer/AVTransport/Control
Unhandled | 2020-06-01 09:36:04.769 | error | promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
sonos.0 | 2020-06-01 09:36:04.638 | info | (20583) try to control id sonos.0.root.192_168_178_36.tts with {"val":"50;http://192.168.178.210:8082/state/sayit.0.tts.mp3","ack":false,"ts":1590996964635,"q":0,"from":"system.adapter.sayit.0","user
sayit.0 | 2020-06-01 09:36:04.632 | info | (20250) Set "sonos.0.root.192_168_178_36.tts: 50;http://192.168.178.210:8082/state/sayit.0.tts.mp3
sayit.0 | 2020-06-01 09:36:04.626 | info | (20250) saying: /opt/iobroker/node_modules/iobroker.sayit/gong.mp3

`

**Comment by Marty56** [comment]
Test mit Sonos Playbar und sayit erzeugen dieselben Fehlermeldungen.

**Comment by DominikReber** [comment]
I have the same issue.

**Comment by tmycgn** [comment]
Same here. :(
