### ISSUE TITLE
Sonos 2.1.0 in Verbindung mit SayIt ohne Funktion

### ISSUE THREAD

**Issue by nicoh88** [ioBroker/ioBroker.sonos#73]
Sonos 1.7.7 hat mit `js-controller@2.2.9` und SayIt problemlos funktioniert.
Sonos 2.1.0 hat mit `js-controller@2.2.9` und SayIt nicht funktioniert.
Sonos 2.1.0 hat mit `js-controller@3.1.4` und SayIt nicht funktioniert.

Habe heute morgen auf `js-controller@3.1.4` aktualisiert.

`Update js-controller from @2.2.9 to @3.1.4`

Da 1.7.7 nicht mit `js-controller@3.1.4` kompatibel ist, musste ich Sonos updaten, damit es überhaupt 🟢 wird. 

Die TTS MP3s werden an Sonos übergeben, sind auch abspielbar (am Computer selber) aber aus dem Sonos Lautsprechern kommt kein Ton mehr. 👎 

Jemand eine Idee?

---

```
sonos.0 | 2020-06-10 06:57:09.058 | info | (12395) try to control id sonos.0.root.192_168_137_40.tts with {"val":"30;http://192.168.137.10:8082/state/sayit.1.tts.mp3","ack":false,"ts":1591765029056,"q":0,"from":"system.adapter.sayit.1","user"
-- | -- | -- | --
sayit.1 | 2020-06-10 06:57:09.054 | info | (5564) Set "sonos.0.root.192_168_137_40.tts: 30;http://192.168.137.10:8082/state/sayit.1.tts.mp3
sayit.1 | 2020-06-10 06:57:09.049 | info | (5564) saying: Das ist ein Test
```

**Comment by nicoh88** [comment]
Die Fehlermeldungen aus #72 kann ich nicht bestätigen.

**Comment by nicoh88** [comment]
Kannst du helfen? @Apollon77

**Comment by Apollon77** [comment]
Hm ... Da ich kein Sonos habe und auch sayit nicht wirklich nutze ist das eher schwierig.

Ideal wäre ein Debug log von einer Kombi die tut mit einer zu vergeichen die nicht tut ... wenn es wirklich der controller ist an dem es liegt wirds noch interessanter und ksnn ggf nur am binary file handling liegen ... was aber getestet ist und tun sollte

**Comment by nicoh88** [comment]
Alles klar. Habe gerade die beiden Adapter auf DEBUG gestellt und wollte testen. JETZT GEHT ES! 😢

Typisch! 🤣 Sorry!

**Comment by Roman310389** [comment]
Hallo nicoh88,
Funktioniert noch alles bei dir? Wo hast du die Adapter auf Debug gestellt ? Bekomme irgendwie keine Ausgabe über die Lautsprecher hin.
