### ISSUE TITLE
Mehrfaches skippen

### ISSUE THREAD

**Issue by gaga191281** [ioBroker/ioBroker.sonos#75]
Ich weiß nicht ob es ein Bug per se ist, oder eine falsche Art der Nutzung meiner Seite.
Aber wenn ich die Datenpunkte 'next' und 'prev' über ein Skript auf true setze, wird nicht wie erwartet nur ein Lied weiter oder zurück geschaltet, sondern gleich mehrfach (jedes mal 17 Titel).
Werden die Datenpunkte jedoch über einen Button im VIS auf true gesetzt, funktioniert es wie erwartet.

**Comment by Apollon77** [comment]
Was macht denn das Skript?

**Comment by gaga191281** [comment]
Jeder Raum hat einen Sonos Lautsprecher. Mein Vis ist so aufgebaut, dass jeder Raum eine eigene Page hat. Die Pages haben eine rudimentäre Playersteuerung für den jeweiligen Lautsprecher. Auf diesen Pages der Räume ist ein drop-down Menü, mit welchem man schnell auswählen, wenn man den Coordinator des Raumes ändern , sprich das selbe wie in einem anderen Raum hören will.
Jetzt sollen natürlich die Control-Buttons, des Slave-Players den Master steuern können und nicht funktionslos sein. Deshalb habe ich ein Skript geschrieben das bei Button-press prüft ob der Player sein eigener Coordinator ist. Wenn nicht führt es die Aktion für den Master aus. 
Das hat bis vor kurzem auch geklappt. Aus irgend einem Grund zeigt es jetzt dieses seltsame mehrfache Skip verhalten auf.

Hoffe das war einiger Maßen verständlich ausgedrückt. :P
