### ISSUE TITLE
Cannot set player volume properly if device is coordinator of a group

### ISSUE THREAD

**Issue by cherberg** [ioBroker/ioBroker.sonos#76]
I discovered that you cannot properly set the player volume of an individual sonos device when it is the coordinator in a sonos group. Example Player Volume is set to 20 and I want to set it to 10, the result is 16.

If the device is not part of a group or if it is a slave in a group with another coordinator it works fine and the entered value is accepted.

Latest stable version 2.1.0 is installed

it would be great if this could be fixed since I am trying to use the Ikea Symfonisk Sound Controller via Phoscon & iobroker to control my sonos per room.

**Comment by gaga191281** [comment]
Which datapoint do you change?

**Comment by cherberg** [comment]
As described: I am trying to change the datapoint: 
player volume / volume or level.volume
 
I don’t know which of these is the proper name of the datapoint.

**Comment by cherberg** [comment]
Is this something that can be fixed?
