### ISSUE TITLE
Von Stream auf Line-in umschalten

### ISSUE THREAD

**Issue by Againstyou** [ioBroker/ioBroker.sonos#77]
Ist es mit dem Adapter möglich von Stream auf Line-in umzuschalten?
Unter dem Datenpunkt: "current_type" gibt es 3 Typen "Type of Stream (0 = track, 1 = radio, 2 = line_in)"
Standartmäßig aber nur lesbar und nicht schreibbar. Man kann sie in IOBroker schreibbar setzen und auch beschreiben. Allerdings ändert dies nichts am realen Typen. Ist es also möglich irgendwie die Quelle selbst umzuschalten?

Ziel wäre es, via Knopfdruck auf einen Zigbee Button von stream(track) auf Line-in zu schalten.

Danke schon mal!

**Comment by mczeus** [comment]
könnte ich auch ganz gut gebrauchen. Erkannt wird es in dem DP "current_type" richtig aber man kann in dort nicht umstellen, dass wäre noch super wenn das möglich wäre!

**Comment by Luedem25** [comment]
Guten Tag
Erstmals vielen Dank für den tollen Adapter und die aufgewendete Zeit. In meiner Systemumgebung funktioniert alles bestens. 

Nun komme ich genau an das oben beschriebene Problem. Gerne würde ich bei einem Sonos-Connect den "current_type" mit einem Blockly-Skript umstellen. Beim "current-type = 2" soll ein externes Signal (Revox-Voxnet) eingespielt werden. Ansonsten werden bei "current-type = 0" MP3 von einem NAS abgespielt.

Gibt's eine Möglichkeit den Adapter um diese Funktion zu erweitern? Im Voraus vielen Dank für die Unterstützung und Rückmeldung.

LG jean

**Comment by Againstyou** [comment]
Push.
Könnte das Feature immer noch brauchen. Ist da was geplant oder gibt es eine andere Möglichkeit?

**Comment by BomBastikDE** [comment]
any new solution for this request?

**Comment by Apollon77** [comment]
The rticket is closed since over 1 year ... dou you really think that it will bring anything to post here? Why you not rsimply open a new request?
