### ISSUE TITLE
js-controller: 3.2.6-0

### ISSUE THREAD

**Issue by RP70DP** [ioBroker/ioBroker.sonos#83]
```
2021-01-12 21:11:24.604  - warn:  sonos.0 (4480) State "sonos.0.root.192_168_0_194.members" has no  existing object, this might lead to an error in future versions
--
2021-01-12 21:11:24.610  - warn:  sonos.0 (4480) State "sonos.0.root.192_168_0_185.members" has no  existing object, this might lead to an error in future versions
```

**Comment by bergjet** [comment]
Version js-controller 3.2.7
`(17852) State "sonos.0.root.192_168_1_26.current_station" has no existing object, this might lead to an error in future versions`

**Comment by RP70DP** [comment]
Hier habe ich nun festgestellt, dass ich meine beiden neuen Sonos-Lautsprecher noch nicht in der Instanz eingetragen hatte, denn für die oben genannten IP-Adressen "192_168_0_194" und "192_168_0_185" gab es gar keine Objekt-Struktur. Nachdem ich die beiden neuen Geräte von der Instanz habe suchen lassen und die Objekt-Struktur nun vorhanden ist, tritt der Fehler natürlich nicht mehr auf.

**Comment by bergjet** [comment]
Mein Objekt ist da.
<img width="1476" alt="Bildschirmfoto 2021-03-15 um 15 18 50" src="https://user-images.githubusercontent.com/4241968/111167898-d7b31a00-85a1-11eb-94c6-a439402909a3.png">

**Comment by RP70DP** [comment]
Log vom Fehler hier posten.

**Comment by bergjet** [comment]
> Log vom Fehler hier posten.
(17852) State "sonos.0.root.192_168_1_26.current_station" has no existing object, this might lead to an error in future versions

**Comment by RP70DP** [comment]
Und der Datenpunkt existiert nicht? Bei mir schon. Mal einfach anlegen. Typ: Zeichenkette, Rolle: media.station

**Comment by bergjet** [comment]
> Und der Datenpunkt existiert nicht? Bei mir schon. Mal einfach anlegen. Typ: Zeichenkette, Rolle: media.station

**Comment by bergjet** [comment]
Habe ich nun angelegt. Nun kommt:
`

sonos.0 | 2021-03-15 18:39:42.862 | warn | (24744) State "sonos.0.root.192_168_1_26.favorites_list_array" has no existing object, this might lead to an error in future versions
-- | -- | -- | --


`

**Comment by RP70DP** [comment]
Adapter stoppen. Den ganzen Baum von 192_168_1_26 löschen. Adapter wieder starten.

**Comment by bergjet** [comment]
> Adapter stoppen. Den ganzen Baum von 192_168_1_26 löschen. Adapter wieder starten.

Danke, hat geholfen. Hätte das bei Netamo auch versucht, dort geht das nicht.

**Comment by RP70DP** [comment]
Jetzt hast du aber noch ein Problem. Den neuen Datenpunkt "queue" kennt der Adapter nicht. Den musst du noch manuell bei jedem Lautsprecher anlegen. Typ: Zeichenkette.

**Comment by RP70DP** [comment]
Problem still exists.

**Comment by GermanBluefox** [comment]
queue muss in 2.1.6 vorhanden sein

**Comment by RP70DP** [comment]
Queue wird nun angelegt, wenn der Objektbaum des Gerätes vorher gelöscht wurde. Kann geschlossen werden.

Eine Rolle gibt es nicht zu dem State?

**Comment by GermanBluefox** [comment]
> Eine Rolle gibt es nicht zu dem State?

Welche sollte man nehmen?

**Comment by RP70DP** [comment]
Ich muss mal gucken, was da drin steht. Ich vermute, dass dort die Titel vermerkt sind, die man in der App zur Liste der nächsten Titel hinzugefügt hat. Vielleicht "media.favorites.array" oder "media.favorites.list". Zumal im State "favorites_list_array" bei mir immer nur "[]" steht. Wie gesagt, ich gucke mal und melde mich wieder.

**Comment by RP70DP** [comment]
Es ist wie von mir vermutet eine Liste mit den Titeln, die man über die Funktionen "Jetzt abspielen", "Danach abspielen" und "Am Listenende einfügen" über die App erzeugt hat. 

Der Datenpunkt ist wie folgt aufgebaut (MP3-Tags):
Interpret - Titel, Interpret - Titel, usw.

Eine bestehende Rolle gibt es wohl nicht.

**Comment by RP70DP** [comment]
"media.favorites.array", "media.favorites.list", "favorites_list_array" entsprechen der Funktion "Mein Sonos" und funktionieren auch.
