### ISSUE TITLE
Adapter startet nicht nach Update von Note.js

### ISSUE THREAD

**Issue by Pitt85** [ioBroker/ioBroker.sonos#90]
Hallo,

nachdem ichNode.js am Raspi auf die aktuelle Version v12.20.2 geupdatet habe, startet der Sonos-Adapter nicht mehr. 
Hat noch jemand das Problem? 
Danke!

**Comment by Apollon77** [comment]
Details bitte, Log bitte. Welche Nodejs version war vorher drauf? Welche js.controller Verison?

**Comment by Pitt85** [comment]
node: v12.20.2, js-controller: 3.2.16



`

host.raspberrypi | 2021-02-13 20:29:29.438 | info | Restart adapter system.adapter.sonos.0 because enabled
-- | -- | -- | --
host.raspberrypi | 2021-02-13 20:29:29.437 | error | instance system.adapter.sonos.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
sonos.0 | 2021-02-13 20:29:29.294 | error | (5911) Cannot read property 'getPlayerByUUID' of null
sonos.0 | 2021-02-13 20:29:29.293 | error | at SAXParser.me._parser.<computed> [as onclosetag] (/opt/iobroker/node_modules/sax/lib/sax.js:258:17)
sonos.0 | 2021-02-13 20:29:29.293 | error | at SAXStream.emit (events.js:314:20)
sonos.0 | 2021-02-13 20:29:29.293 | error | at SAXStream.onCloseTag (/opt/iobroker/node_modules/xml-flow/lib/xml-flow.js:131:15)
sonos.0 | 2021-02-13 20:29:29.293 | error | at EventEmitter.emit (events.js:314:20)
sonos.0 | 2021-02-13 20:29:29.293 | error | at EventEmitter.<anonymous> (/opt/iobroker/node_modules/sonos-discovery/lib/NotificationListener.js:131:13)
sonos.0 | 2021-02-13 20:29:29.293 | error | at NotificationListener.emit (events.js:326:22)
sonos.0 | 2021-02-13 20:29:29.293 | error | at NotificationListener.groupMuteHandler (/opt/iobroker/node_modules/sonos-discovery/lib/models/Player.js:430:18)
sonos.0 | 2021-02-13 20:29:29.293 | error | at SonosSystem.emit (events.js:314:20)
sonos.0 | 2021-02-13 20:29:29.293 | error | at SonosSystem.<anonymous> (/opt/iobroker/node_modules/iobroker.sonos/main.js:1945:9)
sonos.0 | 2021-02-13 20:29:29.293 | error | at processSonosEvents (/opt/iobroker/node_modules/iobroker.sonos/main.js:1648:36)
sonos.0 | 2021-02-13 20:29:29.293 | error | (5911) TypeError: Cannot read property 'getPlayerByUUID' of null
sonos.0 | 2021-02-13 20:29:29.293 | error | (5911) uncaught exception: Cannot read property 'getPlayerByUUID' of null
sonos.0 | 2021-02-13 20:29:29.286 | error | (5911) Cannot read property 'getPlayerByUUID' of null
sonos.0 | 2021-02-13 20:29:29.285 | error | at SAXParser.me._parser.<computed> [as onclosetag] (/opt/iobroker/node_modules/sax/lib/sax.js:258:17)
sonos.0 | 2021-02-13 20:29:29.285 | error | at SAXStream.emit (events.js:314:20)
sonos.0 | 2021-02-13 20:29:29.285 | error | at SAXStream.onCloseTag (/opt/iobroker/node_modules/xml-flow/lib/xml-flow.js:131:15)
sonos.0 | 2021-02-13 20:29:29.285 | error | at EventEmitter.emit (events.js:314:20)
sonos.0 | 2021-02-13 20:29:29.285 | error | at EventEmitter.<anonymous> (/opt/iobroker/node_modules/sonos-discovery/lib/NotificationListener.js:131:13)
sonos.0 | 2021-02-13 20:29:29.285 | error | at NotificationListener.emit (events.js:326:22)
sonos.0 | 2021-02-13 20:29:29.285 | error | at NotificationListener.groupMuteHandler (/opt/iobroker/node_modules/sonos-discovery/lib/models/Player.js:430:18)
sonos.0 | 2021-02-13 20:29:29.285 | error | at SonosSystem.emit (events.js:314:20)
sonos.0 | 2021-02-13 20:29:29.285 | error | at SonosSystem.<anonymous> (/opt/iobroker/node_modules/iobroker.sonos/main.js:1945:9)
sonos.0 | 2021-02-13 20:29:29.285 | error | at processSonosEvents (/opt/iobroker/node_modules/iobroker.sonos/main.js:1648:36)
sonos.0 | 2021-02-13 20:29:29.285 | error | (5911) TypeError: Cannot read property 'getPlayerByUUID' of null
sonos.0 | 2021-02-13 20:29:29.284 | error | (5911) uncaught exception: Cannot read property 'getPlayerByUUID' of null
sonos.0 | 2021-02-13 20:29:29.265 | error | (5911) Cannot read property 'getPlayerByUUID' of null
sonos.0 | 2021-02-13 20:29:29.265 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
sonos.0 | 2021-02-13 20:29:29.265 | error | at /opt/iobroker/node_modules/sonos-discovery/lib/NotificationListener.js:125:17
sonos.0 | 2021-02-13 20:29:29.265 | error | at NotificationListener.emit (events.js:326:22)
sonos.0 | 2021-02-13 20:29:29.265 | error | at NotificationListener.notificationHandler (/opt/iobroker/node_modules/sonos-discovery/lib/models/Player.js:344:20)
sonos.0 | 2021-02-13 20:29:29.265 | error | at SonosSystem.emit (events.js:314:20)
sonos.0 | 2021-02-13 20:29:29.265 | error | at SonosSystem.<anonymous> (/opt/iobroker/node_modules/iobroker.sonos/main.js:1950:9)
sonos.0 | 2021-02-13 20:29:29.265 | error | at processSonosEvents (/opt/iobroker/node_modules/iobroker.sonos/main.js:1707:28)
sonos.0 | 2021-02-13 20:29:29.265 | error | (5911) TypeError: Cannot read property 'getPlayerByUUID' of null
sonos.0 | 2021-02-13 20:29:29.264 | error | (5911) unhandled promise rejection: Cannot read property 'getPlayerByUUID' of null
sonos.0 | 2021-02-13 20:29:29.263 | error | (5911) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
sonos.0 | 2021-02-13 20:29:29.244 | error | (5911) Cannot loadQueue: TypeError: Cannot read property 'getPlayerByUUID' of null
sonos.0 | 2021-02-13 20:29:29.084 | error | (5911) Cannot read property 'getPlayerByUUID' of null
sonos.0 | 2021-02-13 20:29:29.084 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
sonos.0 | 2021-02-13 20:29:29.084 | error | at /opt/iobroker/node_modules/sonos-discovery/lib/NotificationListener.js:125:17
sonos.0 | 2021-02-13 20:29:29.084 | error | at NotificationListener.emit (events.js:326:22)
sonos.0 | 2021-02-13 20:29:29.084 | error | at NotificationListener.notificationHandler (/opt/iobroker/node_modules/sonos-discovery/lib/models/Player.js:344:20)
sonos.0 | 2021-02-13 20:29:29.084 | error | at SonosSystem.emit (events.js:314:20)
sonos.0 | 2021-02-13 20:29:29.084 | error | at SonosSystem.<anonymous> (/opt/iobroker/node_modules/iobroker.sonos/main.js:1950:9)
sonos.0 | 2021-02-13 20:29:29.084 | error | at processSonosEvents (/opt/iobroker/node_modules/iobroker.sonos/main.js:1707:28)
sonos.0 | 2021-02-13 20:29:29.084 | error | (5911) TypeError: Cannot read property 'getPlayerByUUID' of null
sonos.0 | 2021-02-13 20:29:29.083 | error | (5911) unhandled promise rejection: Cannot read property 'getPlayerByUUID' of null
sonos.0 | 2021-02-13 20:29:29.082 | error | (5911) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
sonos.0 | 2021-02-13 20:29:29.055 | error | (5911) Cannot getFavorites: TypeError: Cannot read property 'getFavorites' of null
sonos.0 | 2021-02-13 20:29:29.051 | error | (5911) Cannot getFavorites: TypeError: Cannot read property 'getFavorites' of null
sonos.0 | 2021-02-13 20:29:29.009 | error | (5911) Cannot read property 'getPlayerByUUID' of null
sonos.0 | 2021-02-13 20:29:29.008 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
sonos.0 | 2021-02-13 20:29:29.008 | error | at /opt/iobroker/node_modules/sonos-discovery/lib/NotificationListener.js:117:17
sonos.0 | 2021-02-13 20:29:29.008 | error | at NotificationListener.emit (events.js:314:20)
sonos.0 | 2021-02-13 20:29:29.008 | error | at NotificationListener.topologyChange (/opt/iobroker/node_modules/sonos-discovery/lib/SonosSystem.js:105:11)
sonos.0 | 2021-02-13 20:29:29.008 | error | at SonosSystem.emit (events.js:314:20)
sonos.0 | 2021-02-13 20:29:29.008 | error | at SonosSystem.<anonymous> (/opt/iobroker/node_modules/iobroker.sonos/main.js:1925:9)
sonos.0 | 2021-02-13 20:29:29.008 | error | at processSonosEvents (/opt/iobroker/node_modules/iobroker.sonos/main.js:1566:36)
sonos.0 | 2021-02-13 20:29:29.008 | error | (5911) TypeError: Cannot read property 'getPlayerByUUID' of null
sonos.0 | 2021-02-13 20:29:29.007 | error | (5911) unhandled promise rejection: Cannot read property 'getPlayerByUUID' of null
sonos.0 | 2021-02-13 20:29:29.006 | error | (5911) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
sonos.0 | 2021-02-13 20:29:28.727 | warn | (5911) Terminated (UNCAUGHT_EXCEPTION): Without reason
sonos.0 | 2021-02-13 20:29:28.726 | info | (5911) terminating
sonos.0 | 2021-02-13 20:29:28.724 | info | (5911) terminating
sonos.0 | 2021-02-13 20:29:28.709 | error | (5911) Cannot read property 'replace' of undefined
sonos.0 | 2021-02-13 20:29:28.708 | error | at processImmediate (internal/timers.js:463:21)
sonos.0 | 2021-02-13 20:29:28.708 | error | at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.sonos/main.js:1806:43)
sonos.0 | 2021-02-13 20:29:28.708 | error | (5911) TypeError: Cannot read property 'replace' of undefined
sonos.0 | 2021-02-13 20:29:28.707 | error | (5911) uncaught exception: Cannot read property 'replace' of undefined
sonos.0 | 2021-02-13 20:29:28.592 | info | (5911) starting. Version 2.1.1 in /opt/iobroker/node_modules/iobroker.sonos, node: v12.20.2, js-controller: 3.2.16
host.raspberrypi | 2021-02-13 20:29:27.113 | info | instance system.adapter.sonos.0 started with pid 5911
host.raspberrypi | 2021-02-13 20:29:26.830 | info | "system.adapter.sonos.0" enabled

`

**Comment by Pitt85** [comment]
Habe den Sonos Adapter nochmal neu installiert. Funktioniert wieder. 
Trotzdem Danke!
