### ISSUE TITLE
Erweiterung Adapter - Sonos um: alarmrunning & sleeptimer

### ISSUE THREAD

**Issue by scorpion-1979** [ioBroker/ioBroker.sonos#99]
Hallo zusammen,

ich bin vor kurzem von Openhab auf IoBroker umgestiegen. Soweit habe ich alle Regeln im IoBroker nachgestellt, außer zwei Funktionen, wo mir die Befehle hierzu fehlen:

- alarmrunning 
- sleeptimer

Kann man diese zwei Funktionen ebenfalls im Adapter einbauen? Wäre echt super :-) 

Viele Grüße

Sascha

**Comment by donmike73** [comment]
Adding sleeptimer-support would be great 👍

**Comment by tigerjoerg** [comment]
Wäre weiterhin schön, wenn der Adapter erweitert wird.

Vielen Dank
